packages:
  - apps/*
  - packages/*
  - adapters/*

nodeLinker: isolated
enableGlobalVirtualStore: false
sharedWorkspaceLockfile: true
linkWorkspacePackages: false
saveWorkspaceProtocol: rolling
strictPeerDependencies: true
disallowWorkspaceCycles: true
failIfNoMatch: true
shamefullyHoist: false
publicHoistPattern: []
confirmModulesPurge: false
verifyDepsBeforeRun: warn
allowBuilds:
  sharp: false
