import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import {
  atlasReconciliationRelationshipTypeV1Schema,
  atlasSemanticKindV1Schema,
} from "./atlas-semantic-v1-zod-reference.ts";
import { compileExtractionPrompt } from "./prompt-compiler.mts";
import { createProviderSchema, FROZEN_REFERENCE_SHA256 } from "./provider-schema.mts";

const here = dirname(fileURLToPath(import.meta.url));
const generated = resolve(here, "generated");
const reportPath = resolve(generated, "qualification-report.json");
const kinds = z.enum([
  "actor", "business_object", "business_property", "responsibility", "rule", "constraint", "condition", "decision",
  "workflow_step", "state_transition", "relationship", "input", "output", "acceptance_expectation", "exception", "unresolved",
]);
const expectedKinds = [...kinds.options];
const sourceReference = await readFile(resolve(here, "atlas-semantic-v1-zod-reference.ts"));
const referenceSha256 = digest(sourceReference);
assert.equal(referenceSha256, FROZEN_REFERENCE_SHA256, "frozen reference must match the predecessor-approved hash");

const first = build();
const second = build();
assert.deepEqual(second, first, "two identical offline builds must produce byte-identical schema, prompt, provenance, and hashes");

const checkedIn = {
  providerSchema: await readFile(resolve(generated, "provider-schema.json"), "utf8"),
  systemPrompt: await readFile(resolve(generated, "system-prompt.txt"), "utf8"),
  provenance: await readFile(resolve(generated, "prompt-provenance.json"), "utf8"),
  hashes: await readFile(resolve(generated, "hashes.json"), "utf8"),
};
assert.equal(first.providerSchema, checkedIn.providerSchema, "generated provider schema must match the deterministic build");
assert.equal(first.systemPrompt, checkedIn.systemPrompt, "generated system prompt must match the deterministic build");
assert.equal(first.provenance, checkedIn.provenance, "generated provenance must match the deterministic build");
assert.equal(first.hashes, checkedIn.hashes, "recorded source/schema/prompt hashes must match generated bytes");

const schema = JSON.parse(first.providerSchema) as Record<string, any>;
const prompt = first.systemPrompt;
const kindNode = at(schema, ["properties", "source_results", "items", "properties", "candidates", "items", "properties", "kind"]);
const kindBranches = kindNode.anyOf ?? kindNode.oneOf;
assert.ok(Array.isArray(kindBranches), "provider schema must expose candidate kind alternatives");
const projectedKinds = kindBranches.map((branch: any) => branch.const as string);
assert.deepEqual(projectedKinds, expectedKinds, "provider schema must contain exactly all 16 frozen extraction kinds");
for (const kind of expectedKinds) assert.ok(prompt.includes(kind), `prompt must cover kind ${kind}`);

const candidateFields = at(schema, ["properties", "source_results", "items", "properties", "candidates", "items", "properties"]);
const resultFields = at(schema, ["properties", "source_results", "items", "properties"]);
for (const field of ["semantic_key", "payload", "normalized_meaning", "needs_resolution"]) {
  assert.ok(field in candidateFields, `candidate output must include ${field}`);
  assert.ok(prompt.includes(field), `prompt must describe ${field}`);
}
for (const field of ["classification", "candidates", "non_fact_reason", "questions", "slot"]) {
  assert.ok(field in resultFields, `source result output must include ${field}`);
  assert.ok(prompt.includes(field), `prompt must describe ${field}`);
}
assert.ok(prompt.includes('"candidate"') && prompt.includes('"non_fact"'), "prompt must represent both source classifications");
assert.match(prompt, /kind may remain primary while needs_resolution is true/);
assert.match(prompt, /Kinds can overlap conceptually/);
assert.match(prompt, /PRIMARY semantic role/);
assert.match(prompt, /Preserve the supplied slot exactly/);
assert.match(prompt, /Do not create slots that were not supplied/);
assert.match(prompt, /Do not omit a supplied slot/);
assert.match(prompt, /Do not use non_fact as a fallback for missing or failed extraction/);
assert.doesNotMatch(prompt, /semantic_units\[\]|workflow_step \| rule \| constraint/);
for (const productSpecificTerm of ["jemaah", "umrah", "manifest", "visa", "passport", "Safara-specific statuses"]) {
  assert.ok(!prompt.toLowerCase().includes(productSpecificTerm.toLowerCase()),
    `product-specific corpus term must not enter the generic vocabulary: ${productSpecificTerm}`);
}

const frozenKindSchema = z.toJSONSchema(atlasSemanticKindV1Schema) as any;
const actualFrozenKinds = (frozenKindSchema.anyOf ?? frozenKindSchema.oneOf).map((branch: any) => branch.const).sort();
assert.deepEqual([...projectedKinds].sort(), actualFrozenKinds, "provider vocabulary must match the frozen Zod vocabulary");
const reconciliationSchema = z.toJSONSchema(atlasReconciliationRelationshipTypeV1Schema) as any;
for (const branch of reconciliationSchema.anyOf ?? reconciliationSchema.oneOf ?? []) {
  if (typeof branch.description === "string") {
    assert.ok(!prompt.includes(branch.description), "reconciliation descriptions must not leak into extraction prompt");
  }
}
assert.ok(!("reconciliation" in schema.properties), "provider schema must remain extraction-only");

const sourceSchema = createProviderSchema();
const kindPath = ["properties", "source_results", "items", "properties", "candidates", "items", "properties", "kind", "anyOf"];
const missingKindSchema = structuredClone(sourceSchema) as any;
at(missingKindSchema, kindPath).pop();
assert.throws(() => compileExtractionPrompt(missingKindSchema), /do not exactly match the frozen Zod extraction vocabulary/,
  "qualification must fail when a frozen kind is missing");
const unknownKindSchema = structuredClone(sourceSchema) as any;
at(unknownKindSchema, kindPath).push({ type: "string", const: "invented_kind", description: "invented" });
assert.throws(() => compileExtractionPrompt(unknownKindSchema), /do not exactly match the frozen Zod extraction vocabulary/,
  "qualification must fail when an unknown kind is introduced");

const provenance = JSON.parse(first.provenance) as { sections: any[] };
assert.ok(provenance.sections.length > 0, "provenance must contain generated sections");
for (const section of provenance.sections) {
  assert.ok(section.generatedSection && section.sourceSchemaProperty && section.sourceDescription && section.ownership,
    `provenance section ${section.id} must identify its generated section, source, and owner`);
  if (section.ownership === "STATIC_POLICY") {
    assert.equal(section.sourceSchemaProperty, "(fixed policy)");
  } else {
    assert.ok(section.sourceSchemaProperty && section.sourceDescription,
      `semantic section ${section.id} must map to a source schema property and description`);
  }
  for (const item of section.sourceDescriptions ?? []) {
    assert.ok(section.generatedText.includes(item.sourceDescription),
      `provenance section ${section.id} must preserve the exact source description`);
  }
}

const report = {
  formatVersion: 1,
  checkpoint: "SEM-ANM-PROMPT-002-03",
  result: "PASS",
  coverage: {
    kinds: { expected: expectedKinds, observed: projectedKinds, complete: true },
    providerFields: ["candidate/non_fact", "semantic_key", "payload", "normalized_meaning", "needs_resolution", "questions", "slot/source-result accounting"],
    semanticRules: ["primary-kind/non-exclusive facets", "unresolved versus needs_resolution", "no reconciliation leakage", "no PROMPT-001 ontology", "reference-owned semantic descriptions"],
    negativeCases: ["missing kind rejected", "unknown kind rejected"],
  },
  provenance: {
    sectionCount: provenance.sections.length,
    staticPolicySections: provenance.sections.filter((section) => section.ownership === "STATIC_POLICY").length,
    schemaOwnedSections: provenance.sections.filter((section) => section.ownership !== "STATIC_POLICY").length,
    exactSourceDescriptionsChecked: provenance.sections.reduce((count, section) => count + (section.sourceDescriptions?.length ?? 0), 0),
  },
  determinism: {
    identicalBuilds: 2,
    providerSchemaBytesEqual: true,
    systemPromptBytesEqual: true,
    provenanceBytesEqual: true,
    hashesEqual: true,
    generatedArtifactsMatchBuild: true,
  },
  hashes: {
    ...JSON.parse(first.hashes),
    promptProvenanceSha256: digest(first.provenance),
    qualificationTestSha256: digest(await readFile(resolve(here, "qualification.test.mts"))),
  },
};
await writeFile(reportPath, `${JSON.stringify(report, null, 2)}\n`, "utf8");
console.log(`SEM-ANM-PROMPT-002-03 qualification passed; report=${reportPath}; kinds=${expectedKinds.length}; schema sha256=${report.hashes.providerSchemaSha256}; prompt sha256=${report.hashes.systemPromptSha256}`);

function build() {
  const providerSchema = `${JSON.stringify(createProviderSchema(), null, 2)}\n`;
  const { prompt: renderedPrompt, provenance: renderedProvenance } = compileExtractionPrompt(JSON.parse(providerSchema));
  const systemPrompt = `${renderedPrompt}\n`;
  const provenance = `${JSON.stringify(renderedProvenance, null, 2)}\n`;
  const hashes = `${JSON.stringify({
    referenceSha256,
    providerSchemaSha256: digest(providerSchema),
    systemPromptSha256: digest(systemPrompt),
  }, null, 2)}\n`;
  return { providerSchema, systemPrompt, provenance, hashes };
}

function digest(value: string | Uint8Array): string {
  return createHash("sha256").update(value).digest("hex");
}

function at(value: any, path: string[]): any {
  return path.reduce((current, key) => current[key], value);
}
