import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import test from "node:test";
import postgres from "postgres";
import { PostgresSemanticFoundationRepository } from "../src/semantic-foundation-repository.ts";

const databaseUrl = process.env.DATABASE_URL;
test("semantic foundation preserves bundle scope, lifecycle, and Bridge isolation", { skip: !databaseUrl }, async (t) => {
  const admin = postgres(databaseUrl!, { max: 1 });
  const atlasUrl = new URL(databaseUrl!); atlasUrl.username = "atlas_app"; atlasUrl.password = process.env.ATLAS_APP_PASSWORD ?? "atlas_app_local_dev_only";
  const bridgeUrl = new URL(databaseUrl!); bridgeUrl.username = "agents_bridge"; bridgeUrl.password = process.env.AGENTS_BRIDGE_PASSWORD ?? "agents_bridge_local_dev_only";
  const atlas = postgres(atlasUrl.toString(), { max: 1 });
  const bridge = postgres(bridgeUrl.toString(), { max: 1 });
  const suffix = randomUUID(); const owner = `idser-owner-${suffix}`; const project = `idser-project-${suffix}`; const projectB = `idser-project-b-${suffix}`; const workspace = `idser-draft-${suffix}`; const document = `idser-document-${suffix}`; const bundle = `idser-bundle-${suffix}`;
  try {
    await admin.unsafe('INSERT INTO auth."user" (id, name, email, "emailVerified", "createdAt", "updatedAt") VALUES ($1,$2,$3,false,now(),now())', [owner, owner, `${owner}@example.test`]);
    await atlas.unsafe("INSERT INTO atlas.project (id, stable_id, name, created_by_user_id) VALUES ($1,$2,'IDSER test',$3)", [project, `idser-${suffix.slice(0, 12)}`, owner]);
    await atlas.unsafe("INSERT INTO atlas.workspace (id, project_id, kind, state, display_name) VALUES ($1,$2,'initial_draft','draft','A duplicate display name')", [workspace, project]);
    await atlas.unsafe("INSERT INTO atlas.document (id, project_id, workspace_id, original_filename, storage_key, source_sha256, byte_size, media_type, created_by_user_id) VALUES ($1,$2,$3,'prd.pdf','test/idser',$4,1,'application/pdf',$5)", [document, project, workspace, "a".repeat(64), owner]);
    await atlas.unsafe("INSERT INTO atlas.extraction_bundle (id, project_id, workspace_id, state, semantic_contract_version, reconciliation_contract_version, expected_document_count) VALUES ($1,$2,$3,'waiting','v1','v1',1)", [bundle, project, workspace]);
    await atlas.unsafe("INSERT INTO atlas.extraction_bundle_document (bundle_id, document_id, project_id, workspace_id, sequence, state) VALUES ($1,$2,$3,$4,1,'pending')", [bundle, document, project, workspace]);
    const found = await new PostgresSemanticFoundationRepository(atlas).findBundle(bundle);
    assert.deepEqual(found && { ...found, expectedDocumentCount: Number(found.expectedDocumentCount) }, { id: bundle, projectId: project, workspaceId: workspace, state: "waiting", expectedDocumentCount: 1, completedDocumentCount: 0 });
    const execution = `execution-${suffix}`; const extraction = `extraction-${suffix}`; const candidate = `candidate-${suffix}`; const semantic = `semantic-${suffix}`;
    await atlas.unsafe("INSERT INTO atlas.semantic_execution (id, project_id, workspace_id, bundle_id, document_id, stage, contract_version, skill_version, logical_identity, lifecycle, authorized_context_identity, authorized_context_fingerprint, capability_valid_until) VALUES ($1,$2,$3,$4,$5,'extraction','v1','v1',$1,'queued','context','fingerprint',now()+interval '1 hour')", [execution, project, workspace, bundle, document]);
    await atlas.unsafe("INSERT INTO atlas.semantic_extraction_result (id, execution_id, project_id, workspace_id, bundle_id, document_id, contract_version, source_sha256, provider_provenance, result_json, completion_fingerprint) VALUES ($1,$2,$3,$4,$5,$6,'v1',$7,'{}','{}','done')", [extraction, execution, project, workspace, bundle, document, "a".repeat(64)]);
    await atlas.unsafe("INSERT INTO atlas.semantic_candidate (id, extraction_result_id, project_id, workspace_id, bundle_id, document_id, semantic_key, kind, payload, normalized_meaning, needs_resolution, state) VALUES ($1,$2,$3,$4,$5,$6,'candidate','fact','{}','meaning',true,'candidate')", [candidate, extraction, project, workspace, bundle, document]);
    await atlas.unsafe("INSERT INTO atlas.knowledge_index (semantic_id, project_id, workspace_id, bundle_id, document_id, semantic_key, kind, semantic_candidate_id) VALUES ($1,$2,$3,$4,$5,'candidate','fact',$6)", [semantic, project, workspace, bundle, document, candidate]);
    const workspaceB = `idser-draft-b-${suffix}`; const documentB = `idser-document-b-${suffix}`; const bundleB = `idser-bundle-b-${suffix}`; const executionB = `execution-b-${suffix}`; const extractionB = `extraction-b-${suffix}`; const candidateB = `candidate-b-${suffix}`; const semanticB = `semantic-b-${suffix}`;
    await atlas.unsafe("INSERT INTO atlas.project (id, stable_id, name, created_by_user_id) VALUES ($1,$2,'IDSER test B',$3)", [projectB, `idser-b-${suffix.slice(0, 12)}`, owner]);
    await atlas.unsafe("INSERT INTO atlas.workspace (id, project_id, kind, state, display_name) VALUES ($1,$2,'initial_draft','draft','B')", [workspaceB, projectB]);
    await atlas.unsafe("INSERT INTO atlas.document (id, project_id, workspace_id, original_filename, storage_key, source_sha256, byte_size, media_type, created_by_user_id) VALUES ($1,$2,$3,'prd-b.pdf','test/idser-b',$4,1,'application/pdf',$5)", [documentB, projectB, workspaceB, "b".repeat(64), owner]);
    await atlas.unsafe("INSERT INTO atlas.extraction_bundle (id, project_id, workspace_id, state, semantic_contract_version, reconciliation_contract_version, expected_document_count) VALUES ($1,$2,$3,'waiting','v1','v1',1)", [bundleB, projectB, workspaceB]);
    await atlas.unsafe("INSERT INTO atlas.extraction_bundle_document (bundle_id, document_id, project_id, workspace_id, sequence, state) VALUES ($1,$2,$3,$4,1,'pending')", [bundleB, documentB, projectB, workspaceB]);
    await atlas.unsafe("INSERT INTO atlas.semantic_execution (id, project_id, workspace_id, bundle_id, document_id, stage, contract_version, skill_version, logical_identity, lifecycle, authorized_context_identity, authorized_context_fingerprint, capability_valid_until) VALUES ($1,$2,$3,$4,$5,'extraction','v1','v1',$1,'queued','context','fingerprint',now()+interval '1 hour')", [executionB, projectB, workspaceB, bundleB, documentB]);
    await atlas.unsafe("INSERT INTO atlas.semantic_extraction_result (id, execution_id, project_id, workspace_id, bundle_id, document_id, contract_version, source_sha256, provider_provenance, result_json, completion_fingerprint) VALUES ($1,$2,$3,$4,$5,$6,'v1',$7,'{}','{}','done')", [extractionB, executionB, projectB, workspaceB, bundleB, documentB, "b".repeat(64)]);
    await atlas.unsafe("INSERT INTO atlas.semantic_candidate (id, extraction_result_id, project_id, workspace_id, bundle_id, document_id, semantic_key, kind, payload, normalized_meaning, needs_resolution, state) VALUES ($1,$2,$3,$4,$5,$6,'candidate','fact','{}','meaning',true,'candidate')", [candidateB, extractionB, projectB, workspaceB, bundleB, documentB]);
    await atlas.unsafe("INSERT INTO atlas.knowledge_index (semantic_id, project_id, workspace_id, bundle_id, document_id, semantic_key, kind, semantic_candidate_id) VALUES ($1,$2,$3,$4,$5,'candidate','fact',$6)", [semanticB, projectB, workspaceB, bundleB, documentB, candidateB]);
    const workspace2 = `idser-workspace-2-${suffix}`; const bundle2 = `idser-bundle-2-${suffix}`; const document2 = `idser-document-2-${suffix}`;
    await atlas.unsafe("INSERT INTO atlas.workspace (id, project_id, kind, state, display_name) VALUES ($1,$2,'master','empty','W2')", [workspace2, project]);
    await atlas.unsafe("INSERT INTO atlas.document (id, project_id, workspace_id, original_filename, storage_key, source_sha256, byte_size, media_type, created_by_user_id) VALUES ($1,$2,$3,'prd-2.pdf','test/idser-2',$4,1,'application/pdf',$5)", [document2, project, workspace, "c".repeat(64), owner]);
    await atlas.unsafe("INSERT INTO atlas.extraction_bundle (id, project_id, workspace_id, state, semantic_contract_version, reconciliation_contract_version, expected_document_count) VALUES ($1,$2,$3,'waiting','v1','v1',1)", [bundle2, project, workspace]);
    await atlas.unsafe("INSERT INTO atlas.extraction_bundle_document (bundle_id, document_id, project_id, workspace_id, sequence, state) VALUES ($1,$2,$3,$4,2,'pending')", [bundle, document2, project, workspace]);
    await atlas.unsafe("INSERT INTO atlas.extraction_bundle_document (bundle_id, document_id, project_id, workspace_id, sequence, state) VALUES ($1,$2,$3,$4,1,'pending')", [bundle2, document, project, workspace]);
    const execution2 = `execution-2-${suffix}`; const extraction2 = `extraction-2-${suffix}`; const candidate2 = `candidate-2-${suffix}`; const semantic2 = `semantic-2-${suffix}`;
    await atlas.unsafe("INSERT INTO atlas.semantic_execution (id, project_id, workspace_id, bundle_id, document_id, stage, contract_version, skill_version, logical_identity, lifecycle, authorized_context_identity, authorized_context_fingerprint, capability_valid_until) VALUES ($1,$2,$3,$4,$5,'extraction','v1','v1',$1,'queued','context','fingerprint',now()+interval '1 hour')", [execution2, project, workspace, bundle2, document]);
    await atlas.unsafe("INSERT INTO atlas.semantic_extraction_result (id, execution_id, project_id, workspace_id, bundle_id, document_id, contract_version, source_sha256, provider_provenance, result_json, completion_fingerprint) VALUES ($1,$2,$3,$4,$5,$6,'v1',$7,'{}','{}','done')", [extraction2, execution2, project, workspace, bundle2, document, "a".repeat(64)]);
    await atlas.unsafe("INSERT INTO atlas.semantic_candidate (id, extraction_result_id, project_id, workspace_id, bundle_id, document_id, semantic_key, kind, payload, normalized_meaning, needs_resolution, state) VALUES ($1,$2,$3,$4,$5,$6,'candidate-2','fact','{}','meaning',true,'candidate')", [candidate2, extraction2, project, workspace, bundle2, document]);
    await atlas.unsafe("INSERT INTO atlas.knowledge_index (semantic_id, project_id, workspace_id, bundle_id, document_id, semantic_key, kind, semantic_candidate_id) VALUES ($1,$2,$3,$4,$5,'candidate-2','fact',$6)", [semantic2, project, workspace, bundle2, document, candidate2]);
    const document3 = `idser-document-3-${suffix}`; const bundle3 = `idser-bundle-3-${suffix}`; const execution3 = `execution-3-${suffix}`; const extraction3 = `extraction-3-${suffix}`; const candidate3 = `candidate-3-${suffix}`; const semantic3 = `semantic-3-${suffix}`;
    await atlas.unsafe("INSERT INTO atlas.document (id, project_id, workspace_id, original_filename, storage_key, source_sha256, byte_size, media_type, created_by_user_id) VALUES ($1,$2,$3,'prd-3.pdf','test/idser-3',$4,1,'application/pdf',$5)", [document3, project, workspace2, "d".repeat(64), owner]);
    await atlas.unsafe("INSERT INTO atlas.extraction_bundle (id, project_id, workspace_id, state, semantic_contract_version, reconciliation_contract_version, expected_document_count) VALUES ($1,$2,$3,'waiting','v1','v1',1)", [bundle3, project, workspace2]);
    await atlas.unsafe("INSERT INTO atlas.extraction_bundle_document (bundle_id, document_id, project_id, workspace_id, sequence, state) VALUES ($1,$2,$3,$4,1,'pending')", [bundle3, document3, project, workspace2]);
    await atlas.unsafe("INSERT INTO atlas.semantic_execution (id, project_id, workspace_id, bundle_id, document_id, stage, contract_version, skill_version, logical_identity, lifecycle, authorized_context_identity, authorized_context_fingerprint, capability_valid_until) VALUES ($1,$2,$3,$4,$5,'extraction','v1','v1',$1,'queued','context','fingerprint',now()+interval '1 hour')", [execution3, project, workspace2, bundle3, document3]);
    await atlas.unsafe("INSERT INTO atlas.semantic_extraction_result (id, execution_id, project_id, workspace_id, bundle_id, document_id, contract_version, source_sha256, provider_provenance, result_json, completion_fingerprint) VALUES ($1,$2,$3,$4,$5,$6,'v1',$7,'{}','{}','done')", [extraction3, execution3, project, workspace2, bundle3, document3, "d".repeat(64)]);
    await atlas.unsafe("INSERT INTO atlas.semantic_candidate (id, extraction_result_id, project_id, workspace_id, bundle_id, document_id, semantic_key, kind, payload, normalized_meaning, needs_resolution, state) VALUES ($1,$2,$3,$4,$5,$6,'candidate-3','fact','{}','meaning',true,'candidate')", [candidate3, extraction3, project, workspace2, bundle3, document3]);
    await atlas.unsafe("INSERT INTO atlas.knowledge_index (semantic_id, project_id, workspace_id, bundle_id, document_id, semantic_key, kind, semantic_candidate_id) VALUES ($1,$2,$3,$4,$5,'candidate-3','fact',$6)", [semantic3, project, workspace2, bundle3, document3, candidate3]);
    await atlas.unsafe("UPDATE atlas.extraction_bundle SET state='processing', started_at=now() WHERE id=$1", [bundle]);
    await atlas.unsafe("UPDATE atlas.extraction_bundle_document SET state='perceiving', started_at=now(), perception_execution_id=$3 WHERE bundle_id=$1 AND document_id=$2", [bundle, document, `perception-${suffix}`]);
    await assert.rejects(() => atlas.unsafe("UPDATE atlas.extraction_bundle_document SET sequence=3 WHERE bundle_id=$1 AND document_id=$2", [bundle, document]), /immutable/i);
    const assertCandidateScope = (sql: Promise<unknown>) => assert.rejects(sql, (error: any) => error.code === "23503" && error.constraint_name === "knowledge_index_candidate_scope_fkey");
    await assertCandidateScope(atlas.unsafe("UPDATE atlas.knowledge_index SET project_id=$2 WHERE semantic_id=$1", [semantic, projectB]));
    await assertCandidateScope(atlas.unsafe("UPDATE atlas.knowledge_index SET workspace_id=$2 WHERE semantic_id=$1", [semantic, workspace2]));
    await assertCandidateScope(atlas.unsafe("UPDATE atlas.knowledge_index SET bundle_id=$2 WHERE semantic_id=$1", [semantic, bundle2]));
    await assertCandidateScope(atlas.unsafe("UPDATE atlas.knowledge_index SET document_id=$2 WHERE semantic_id=$1", [semantic, document2]));
    const reconciliationExecution = `reconciliation-${suffix}`; const reconciliationResult = `reconciliation-result-${suffix}`;
    await atlas.unsafe("INSERT INTO atlas.semantic_execution (id, project_id, workspace_id, bundle_id, document_id, stage, contract_version, skill_version, logical_identity, lifecycle, authorized_context_identity, authorized_context_fingerprint, capability_valid_until) VALUES ($1,$2,$3,$4,$5,'reconciliation','v1','v1',$1,'queued','context','fingerprint',now()+interval '1 hour')", [reconciliationExecution, project, workspace, bundle, document]);
    await atlas.unsafe("INSERT INTO atlas.semantic_reconciliation_result (id, execution_id, project_id, workspace_id, bundle_id, current_document_id, contract_version, provider_provenance, result_json, completion_fingerprint) VALUES ($1,$2,$3,$4,$5,$6,'v1','{}','{}','done')", [reconciliationResult, reconciliationExecution, project, workspace, bundle, document]);
    const insertRelationship = (id: string, target: string | null) => atlas.unsafe("INSERT INTO atlas.reconciliation_relationship (id, reconciliation_result_id, project_id, workspace_id, bundle_id, source_semantic_id, target_semantic_id, relationship_type, payload, requires_resolution) VALUES ($1,$2,$3,$4,$5,$6,$7,'related','{}',true)", [id, reconciliationResult, project, workspace, bundle, semantic, target]);
    await insertRelationship(`relationship-same-${suffix}`, semantic);
    await insertRelationship(`relationship-null-${suffix}`, null);
    const assertRelationshipTargetScope = (target: string) => assert.rejects(() => insertRelationship(`relationship-cross-${target}-${suffix}`, target), (error: any) => error.code === "23503" && error.constraint_name === "reconciliation_relationship_target_scope_fkey");
    await assertRelationshipTargetScope(semantic2);
    await assertRelationshipTargetScope(semantic3);
    await assertRelationshipTargetScope(semanticB);
    await assert.rejects(() => bridge.unsafe("SELECT * FROM atlas.extraction_bundle"), /permission denied/i);
    await bridge.unsafe("INSERT INTO bridge.semantic_result_delivery (idempotency_key, execution_id, stage, validated_envelope, provenance, completion_fingerprint) VALUES ($1,$2,'extraction','{}','{}','fingerprint')", [`delivery-${suffix}`, `execution-${suffix}`]);
  } catch (error) {
    t.diagnostic(error instanceof Error ? `${error.name}: ${error.message}` : String(error));
    throw error;
  } finally {
    await bridge.unsafe("DELETE FROM bridge.semantic_result_delivery WHERE idempotency_key=$1", [`delivery-${suffix}`]);
    const fixtureProjects = "project_id=$1 OR project_id=$2";
    const fixtureArgs = [project, projectB];
    await admin.unsafe(`DELETE FROM atlas.reconciliation_relationship WHERE ${fixtureProjects}`, fixtureArgs);
    await admin.unsafe(`DELETE FROM atlas.semantic_reconciliation_result WHERE ${fixtureProjects}`, fixtureArgs);
    await admin.unsafe(`DELETE FROM atlas.knowledge_index WHERE ${fixtureProjects}`, fixtureArgs);
    await admin.unsafe(`DELETE FROM atlas.semantic_evidence WHERE semantic_candidate_id IN (SELECT id FROM atlas.semantic_candidate WHERE ${fixtureProjects})`, fixtureArgs);
    await admin.unsafe(`DELETE FROM atlas.semantic_candidate WHERE ${fixtureProjects}`, fixtureArgs);
    await admin.unsafe(`DELETE FROM atlas.semantic_extraction_result WHERE ${fixtureProjects}`, fixtureArgs);
    await admin.unsafe(`DELETE FROM atlas.semantic_execution WHERE ${fixtureProjects}`, fixtureArgs);
    await admin.unsafe(`UPDATE atlas.extraction_bundle SET state='waiting', started_at=NULL, completed_at=NULL WHERE ${fixtureProjects}`, fixtureArgs);
    await admin.unsafe(`DELETE FROM atlas.extraction_bundle_document WHERE ${fixtureProjects}`, fixtureArgs);
    await admin.unsafe(`DELETE FROM atlas.extraction_bundle WHERE ${fixtureProjects}`, fixtureArgs);
    await admin.unsafe(`DELETE FROM atlas.document WHERE ${fixtureProjects}`, fixtureArgs);
    await admin.unsafe(`DELETE FROM atlas.workspace WHERE ${fixtureProjects}`, fixtureArgs);
    await admin.unsafe("DELETE FROM atlas.project WHERE id=$1 OR id=$2", fixtureArgs);
    const [{ count: remainingFixtures }] = await admin.unsafe("SELECT count(*) AS count FROM atlas.project WHERE id=$1 OR id=$2", fixtureArgs);
    assert.equal(Number(remainingFixtures), 0, "fixture projects must be removed during teardown");
    await admin.unsafe('DELETE FROM auth."user" WHERE id=$1', [owner]);
    await Promise.all([admin.end(), atlas.end(), bridge.end()]);
  }
});
