import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createValidatedFixture } from "../groq-semantic-spike-002/fixture.mts";
import { finalize } from "../groq-semantic-spike-002/finalize.mts";
import { validateIntermediate } from "../groq-semantic-spike-002/intermediate-schema.mts";
import { assertSemanticOracle, semanticDecisionSignature } from "../groq-semantic-spike-002/semantic-oracle.mts";
import { invokeGroq } from "./groq-client.mts";
const out = resolve(".atlas-data/groq-semantic-spike-003"), write = async (name: string, value: unknown) => writeFile(resolve(out, name), `${JSON.stringify(value, null, 2)}\n`);
await mkdir(out, { recursive: true }); await write("fixture.normalized.json", createValidatedFixture()); const runs: any[] = [];
for (const run of [1, 2]) { try { const live = await invokeGroq(), proposal = validateIntermediate(live.proposal), final_result = finalize(proposal); try { assertSemanticOracle(proposal); runs.push({ run, ...live.metrics, parser_result: "PASS", source_accounting: "PASS", semantic_oracle: "PASS", proposal, final_result }); } catch (error) { runs.push({ run, ...live.metrics, parser_result: "PASS", source_accounting: "PASS", semantic_oracle: "FAIL", error: error instanceof Error ? error.message : "Unknown failure", proposal, final_result }); } } catch (error) { runs.push({ run, parser_result: "NOT_RUN", source_accounting: "FAIL", semantic_oracle: "NOT_RUN", error: error instanceof Error ? error.message : "Unknown failure" }); } await write(`run-${run}.json`, runs.at(-1)); }
const valid = runs.filter((run) => run.semantic_oracle === "PASS"), same = valid.length === 2 && JSON.stringify(semanticDecisionSignature(valid[0].proposal)) === JSON.stringify(semanticDecisionSignature(valid[1].proposal)); const summary = { classification: same ? "PASS" : "FAIL", authenticated_live_inference: runs.some((run) => run.http_status) ? "yes" : "no", repeatability: same ? "materially consistent" : "not qualified because an oracle failed or decisions differed", runs: runs.map(({ run, provider, model, http_status, latency_ms, input_tokens, output_tokens, parser_result, source_accounting, semantic_oracle, error }) => ({ run, provider, model, http_status, latency_ms, input_tokens, output_tokens, parser_result, source_accounting, semantic_oracle, error })) }; await write("summary.json", summary); console.log(JSON.stringify(summary)); if (!same) process.exitCode = 2;
