import Ajv from "ajv/dist/ajv.js";
import { normalizedDocumentSchema, type NormalizedDocument } from "./perception.js";
import { atlasSemanticExtractionResultV1JsonSchema, atlasSemanticExtractionResultV1Schema, atlasSemanticReconciliationResultV1JsonSchema, atlasSemanticReconciliationResultV1Schema, semanticKinds } from "./semantic-v1.js";

type Validator = ((value: unknown) => boolean) & { readonly errors?: unknown };
type AjvInstance = { compile(schema: object): Validator; errorsText(errors: unknown): string };
const AjvConstructor = Ajv as unknown as new (options: { readonly allErrors: boolean; readonly strict: boolean }) => AjvInstance;
const ajv = new AjvConstructor({ allErrors: true, strict: false });

export const semanticContractVersion = "v1" as const;
export const semanticSkillIds = ["atlas.semantic.extract", "atlas.semantic.reconcile"] as const;
export type SemanticSkillId = typeof semanticSkillIds[number];
export const semanticLimits = {
  jobBytes: 16 * 1024, contextBytes: 1024 * 1024, resultEnvelopeBytes: 2 * 1024 * 1024,
  currentCandidates: 500, priorCandidates: 500, totalCandidates: 1000, retrievalPage: 100,
} as const;

const id = { type: "string", minLength: 1, maxLength: 200, pattern: "^[A-Za-z0-9][A-Za-z0-9._:-]{0,199}$" } as const;
const text = (maxLength: number) => ({ type: "string", minLength: 1, maxLength });
const jsonValue = { anyOf: [{ type: "null" }, { type: "boolean" }, { type: "number" }, { type: "string", maxLength: 16384 }, { type: "array", maxItems: 100, items: {} }, { type: "object", maxProperties: 100, additionalProperties: {} }] } as const;
const scopeSchema = { type: "object", additionalProperties: false, required: ["projectId", "workspaceId", "bundleId", "documentId", "executionId", "contractVersion"], properties: { projectId: id, workspaceId: id, bundleId: id, documentId: id, executionId: id, contractVersion: { const: semanticContractVersion } } } as const;
const evidenceRefSchema = { type: "object", additionalProperties: false, required: ["page_number", "locator_type", "locator_id"], properties: { page_number: { type: "integer", minimum: 1 }, locator_type: { enum: ["text_block", "table", "visual_region"] }, locator_id: id, excerpt: { type: "string", minLength: 1, maxLength: 4000 } }, allOf: [{ if: { properties: { locator_type: { enum: ["text_block", "table"] } } }, then: { required: ["excerpt"] } }] } as const;
export const semanticExtractionResultSchema = atlasSemanticExtractionResultV1JsonSchema;
export const semanticReconciliationResultSchema = atlasSemanticReconciliationResultV1JsonSchema;
const semanticJsonDefinitions = (semanticExtractionResultSchema as { readonly definitions?: object }).definitions;

export const semanticBackgroundJobSchema = { type: "object", additionalProperties: false, required: ["version", "executionId", "skill", "contextCapability"], properties: { version: { const: semanticContractVersion }, executionId: id, skill: { type: "object", additionalProperties: false, required: ["id", "version"], properties: { id: { enum: semanticSkillIds }, version: { const: semanticContractVersion } } }, contextCapability: text(1000) } } as const;
export const semanticExtractionContextSchema = { type: "object", additionalProperties: false, required: ["version", "skill", "scope", "normalizedDocument"], properties: { version: { const: semanticContractVersion }, skill: { const: "atlas.semantic.extract" }, scope: scopeSchema, normalizedDocument: normalizedDocumentSchema } } as const;
const contextCandidateSchema = { type: "object", additionalProperties: false, required: ["id", "semantic_key", "kind", "normalized_meaning", "payload", "evidence_refs"], properties: { id, semantic_key: text(300), kind: { enum: semanticKinds }, normalized_meaning: text(8000), payload: jsonValue, evidence_refs: { type: "array", maxItems: 32, items: evidenceRefSchema } } } as const;
export const semanticReconciliationContextSchema = { type: "object", additionalProperties: false, required: ["version", "skill", "scope", "currentCandidates", "priorCandidates", "selection"], properties: { version: { const: semanticContractVersion }, skill: { const: "atlas.semantic.reconcile" }, scope: scopeSchema, currentCandidates: { type: "array", maxItems: semanticLimits.currentCandidates, items: contextCandidateSchema }, priorCandidates: { type: "array", maxItems: semanticLimits.priorCandidates, items: contextCandidateSchema }, selection: { type: "object", additionalProperties: false, required: ["policy", "version", "overflow", "selectedCount", "currentCount", "totalCount", "byteLimit", "byteCount", "omittedPriorCount"], properties: { policy: text(200), version: { const: "v1" }, overflow: { type: "boolean" }, selectedCount: { type: "integer", minimum: 0, maximum: semanticLimits.priorCandidates }, currentCount: { type: "integer", minimum: 0, maximum: semanticLimits.currentCandidates }, totalCount: { type: "integer", minimum: 0, maximum: semanticLimits.totalCandidates }, byteLimit: { const: semanticLimits.contextBytes }, byteCount: { type: "integer", minimum: 0, maximum: semanticLimits.contextBytes }, omittedPriorCount: { type: "integer", minimum: 0 } } }, acceptedBaseCandidates: { type: "array", maxItems: 0 } } } as const;
export const semanticResultEnvelopeSchema = { type: "object", additionalProperties: false, required: ["version", "scope", "skill", "provider", "result"], properties: { version: { const: semanticContractVersion }, scope: scopeSchema, skill: { type: "object", additionalProperties: false, required: ["id", "version"], properties: { id: { enum: semanticSkillIds }, version: { const: semanticContractVersion } } }, provider: { type: "object", additionalProperties: false, required: ["provider", "model", "endpoint", "latencyMilliseconds", "attempt"], properties: { provider: text(100), model: text(200), endpoint: text(500), latencyMilliseconds: { type: "integer", minimum: 0 }, attempt: { type: "integer", minimum: 1 }, usage: jsonValue } }, result: { oneOf: [semanticExtractionResultSchema, semanticReconciliationResultSchema] } }, ...(semanticJsonDefinitions ? { definitions: semanticJsonDefinitions } : {}) } as const;
export const semanticTechnicalFailureSchema = { type: "object", additionalProperties: false, required: ["version", "scope", "code", "message"], properties: { version: { const: semanticContractVersion }, scope: scopeSchema, code: { enum: ["context_authorization", "context_bound", "provider_unavailable", "provider_timeout", "malformed_output", "schema_validation", "integrity_validation", "completion_conflict"] }, message: text(1000) } } as const;

export type SemanticBackgroundJob = { readonly version: "v1"; readonly executionId: string; readonly skill: { readonly id: SemanticSkillId; readonly version: "v1" }; readonly contextCapability: string };
export type SemanticExtractionContext = { readonly version: "v1"; readonly skill: "atlas.semantic.extract"; readonly scope: Record<string, string>; readonly normalizedDocument: NormalizedDocument };
export type SemanticReconciliationContext = { readonly version: "v1"; readonly skill: "atlas.semantic.reconcile"; readonly scope: Record<string, string>; readonly currentCandidates: readonly unknown[]; readonly priorCandidates: readonly unknown[]; readonly selection: { readonly policy: string; readonly version: "v1"; readonly overflow: boolean; readonly selectedCount: number; readonly currentCount: number; readonly totalCount: number; readonly byteLimit: number; readonly byteCount: number; readonly omittedPriorCount: number } };
export type SemanticExtractionResult = ReturnType<typeof atlasSemanticExtractionResultV1Schema.parse>;
export type SemanticReconciliationResult = ReturnType<typeof atlasSemanticReconciliationResultV1Schema.parse>;

const validators = { job: ajv.compile(semanticBackgroundJobSchema), extractionContext: ajv.compile(semanticExtractionContextSchema), reconciliationContext: ajv.compile(semanticReconciliationContextSchema), extractionResult: ajv.compile(semanticExtractionResultSchema), reconciliationResult: ajv.compile(semanticReconciliationResultSchema), envelope: ajv.compile(semanticResultEnvelopeSchema), failure: ajv.compile(semanticTechnicalFailureSchema) };
function parse<T>(validator: Validator, value: unknown, label: string, maximumBytes: number): T { assertUtf8JsonBytes(value, maximumBytes, label); if (!validator(value)) throw new Error(`Invalid ${label}: ${ajv.errorsText(validator.errors)}`); return value as T; }
export function assertUtf8JsonBytes(value: unknown, maximumBytes: number, label = "semantic value"): void { let serialized: string; try { serialized = JSON.stringify(value); } catch { throw new Error(`Invalid ${label}: not JSON serializable`); } if (new TextEncoder().encode(serialized).byteLength > maximumBytes) throw new Error(`Invalid ${label}: exceeds ${maximumBytes} UTF-8 JSON bytes`); }
function assertBoundedPayload(value: unknown, depth = 0): void {
  if (depth > 8) throw new Error("Invalid semantic payload: exceeds nesting depth 8");
  if (typeof value === "string" && value.length > 16384) throw new Error("Invalid semantic payload: string exceeds limit");
  if (Array.isArray(value)) { if (value.length > 100) throw new Error("Invalid semantic payload: array exceeds limit"); for (const item of value) assertBoundedPayload(item, depth + 1); return; }
  if (value && typeof value === "object") { const entries = Object.values(value); if (entries.length > 100) throw new Error("Invalid semantic payload: object exceeds limit"); for (const item of entries) assertBoundedPayload(item, depth + 1); }
}
export function parseSemanticBackgroundJob(value: unknown): SemanticBackgroundJob { return parse<SemanticBackgroundJob>(validators.job, value, "semantic background job", semanticLimits.jobBytes); }
export function parseSemanticExtractionContext(value: unknown): SemanticExtractionContext { const parsed = parse<SemanticExtractionContext>(validators.extractionContext, value, "semantic extraction context", semanticLimits.contextBytes); if (parsed.scope.documentId !== parsed.normalizedDocument.artifactId) throw new Error("Invalid semantic extraction context: scope document does not match normalized document"); return parsed; }
export function parseSemanticReconciliationContext(value: unknown): SemanticReconciliationContext { const parsed = parse<SemanticReconciliationContext>(validators.reconciliationContext, value, "semantic reconciliation context", semanticLimits.contextBytes); if (parsed.currentCandidates.length + parsed.priorCandidates.length > semanticLimits.totalCandidates) throw new Error("Invalid semantic reconciliation context: candidate total exceeds limit"); for (const candidate of [...parsed.currentCandidates, ...parsed.priorCandidates]) assertBoundedPayload((candidate as { readonly payload: unknown }).payload); return parsed; }
export function parseSemanticExtractionResult(value: unknown): SemanticExtractionResult { assertUtf8JsonBytes(value, semanticLimits.resultEnvelopeBytes, "semantic extraction result"); const parsed = atlasSemanticExtractionResultV1Schema.safeParse(value); if (!parsed.success) throw new Error(`Invalid semantic extraction result: ${parsed.error.message}`); return parsed.data; }
export function parseSemanticReconciliationResult(value: unknown): SemanticReconciliationResult { assertUtf8JsonBytes(value, semanticLimits.resultEnvelopeBytes, "semantic reconciliation result"); const parsed = atlasSemanticReconciliationResultV1Schema.safeParse(value); if (!parsed.success) throw new Error(`Invalid semantic reconciliation result: ${parsed.error.message}`); return parsed.data; }
export function parseSemanticResultEnvelope(value: unknown): unknown {
  const parsed = parse(validators.envelope, value, "semantic result envelope", semanticLimits.resultEnvelopeBytes) as { skill: { id: SemanticSkillId }; result: unknown };
  if (parsed.skill.id === "atlas.semantic.extract") parseSemanticExtractionResult(parsed.result); else parseSemanticReconciliationResult(parsed.result);
  return parsed;
}
export function parseSemanticTechnicalFailure(value: unknown): unknown { return parse(validators.failure, value, "semantic technical failure", semanticLimits.jobBytes); }
