import projectFixtureRegistry from "../generated/project-card-fixtures.json" with { type: "json" };
export { resolveFixtureAuthoringExecutor, resolveSkillsMode, type AgentsBridgeExecutor, type SkillsMode } from "./skills-mode.ts";
export { resolveGoldenFixtureBranch, type GoldenFixtureBundle } from "./golden-fixture.ts";
export { completeSfeExtraction, failSfeExtraction, validateSfeExtraction, type CompletedFixtureProject, type ExtractionMode, type SfeCandidate, type SfeExtractionResult, type SfeInventoryEntry, type SfeProjectInput, type SfeSourceArtifact } from "./sfe-extraction.ts";
export type AccessRole="owner"|"editor"|"viewer"; export type ProjectStatus="ready"|"processing"|"needs-attention"; export type RepositoryLifecycleState="published"|"extracting"|"ready-for-review"|"needs-attention"; export type ProcessingStage="uploading"|"extracting"|"modeling"|"ready"|"needs-attention"|"failed"; export type ApprovalState="awaiting-approval"|"approved"; export type CesCoverageState="covered"|"needs-review"|"out-of-scope"|"unresolved"; export type ChangeKind="established"|"clarified"|"expanded"|"superseded"|"unresolved";
export type PrdFileMetadata={name:string;type:"application/pdf";size:number}; export type StoredPrdFileMetadata=PrdFileMetadata&{relativePath:string;sha256:string}; export type ProjectCreateRequest={projectId:string;projectName:string;projectDescription:string;prdFiles:PrdFileMetadata[]}; export type EmptyMasterWorkspaceFixture={workspaceId:"master";projectId:string;workspaceName:"Master";status:"empty";prdFiles:[]}; export type InitialDraftWorkspaceFixture={workspaceId:string;projectId:string;workspaceName:"Initial Draft";status:"extracting";available:false;unavailableReason:string;prdFiles:PrdFileMetadata[]}; export type ProjectPrdRecord={projectId:string;workspaceId:string;prdFiles:PrdFileMetadata[]}; export type CreatedFixtureProject={project:ProjectFixture;processingJob:ProcessingJobFixture;request:ProjectCreateRequest;masterWorkspace:EmptyMasterWorkspaceFixture;initialDraftWorkspace:InitialDraftWorkspaceFixture;prdRecord:ProjectPrdRecord};
export type WorkspaceCreationBase={workspaceId:string;projectId:string;baseWorkspaceId?:string;headRevisionId:string}; export type WorkspaceCreationRequest={projectId:string;workspaceName:string;baseWorkspaceId:string;prdFiles:PrdFileMetadata[]}; export type CreatedWorkspaceFixture={workspaceId:string;projectId:string;workspaceName:string;baseWorkspaceId:string;baseHeadRevisionId:string;status:"extracting";available:false;unavailableReason:string;prdFiles:PrdFileMetadata[]}; export type ReadyForReviewWorkspaceFixture=Omit<CreatedWorkspaceFixture,"status"|"available"|"unavailableReason">&{status:"ready-for-review";available:true;unavailableReason?:undefined}; export type WorkspaceExtractionRequest={workspaceId:string;projectId:string;baseWorkspaceId:string;baseHeadRevisionId:string;prdFiles:PrdFileMetadata[]}; export type CreatedWorkspaceRequest={workspace:CreatedWorkspaceFixture;extractionRequest:WorkspaceExtractionRequest};
export type SourceEvidence={id:string;understood:string;quote:string;documentId:string;documentName:string;page:number}; export type PrdFixture={id:string;name:string;increment:string;publishedAt:string;pageCount:number;selectedByDefault?:boolean}; export type ProjectMetricFixture={value:string;label:string}; export type ProjectRepositoryFixture={state:RepositoryLifecycleState;summary:string;master:{state:"published"|"empty";summary:string;detail:string};initialDraft?:{processedPrds:number;totalPrds:number;progress:number};metrics:[ProjectMetricFixture,ProjectMetricFixture,ProjectMetricFixture];action:{label:string;enabled:boolean;unavailableReason?:string}}; export type ProjectFixture={id:string;name:string;status:ProjectStatus;prdCount:number;collaborators:number;lastActivity:string;isShared:boolean;repository:ProjectRepositoryFixture}; export type MembershipFixture={id:string;name:string;email:string;role:AccessRole;status:"active"|"invited"|"removed"}; export type WorkflowNodeFixture={id:string;title:string;note:string;kind:"activity"|"decision"|"outcome"|"warning";prdIds:string[];evidence:SourceEvidence}; export type WorkflowFixture={id:string;groupId:string;title:string;summary:string;businessQuestion:string;roles:string[];expectedResult:string;prdIds:string[];relatedFactIds:string[];nodes:WorkflowNodeFixture[];evidence:SourceEvidence[]}; export type WorkflowGroupFixture={id:string;order:string;title:string;summary:string;expectedResult:string;roles:string[];workflowIds:string[];prdIds:string[];support?:boolean}; export type FactRowFixture={id:string;statement:string;prdIds:string[];relatedWorkflowIds:string[];cesItemIds:string[];evidence:SourceEvidence[]}; export type FactFixture={id:string;number:string;title:"Scope"|"People and responsibilities"|"Constraints"|"Information protection"|"Outputs"|"Commitments";summary:string;prdIds:string[];rows:FactRowFixture[]}; export type ChangeDestination={type:"workflow"|"fact"|"ces"|"project"|"unresolved";targetId?:string;label:string}; export type ChangeFixture={id:string;kind:ChangeKind;title:string;summary:string;prdId:string;destination:ChangeDestination;evidence:SourceEvidence[]}; export type SourceAccountingStatement={id:string;prdId:string;statement:string;destination:ChangeDestination;evidence:SourceEvidence[]}; export type CesItemFixture={id:string;policyId:string;policy:string;rule:string;conclusion:string;obligation:string;sourcePrdIds:string[];linkedFactIds:string[];relatedWorkflowIds:string[];concern:string;capabilityNeed:string;coverage:CesCoverageState;decision?:string;destination:ChangeDestination;evidence:SourceEvidence[]}; export type ProcessingJobFixture={id:string;projectId:string;workspaceId:string;stage:ProcessingStage;message:string;progress:number};
export type ProjectWorkspaceFixture={project:ProjectFixture;prds:PrdFixture[];memberships:MembershipFixture[];workflowGroups:WorkflowGroupFixture[];workflows:WorkflowFixture[];facts:FactFixture[];changes:ChangeFixture[];sourceAccounting:SourceAccountingStatement[];cesItems:CesItemFixture[];atlasApproval:ApprovalState;cesApproval:ApprovalState}; export type FixtureScenario={id:"empty-library"|"owner-ready"|"editor-ready"|"viewer-ready"|"processing-uploading"|"processing-extracting"|"processing-modeling"|"processing-ready"|"processing-needs-attention"|"processing-failed"|"approved-result";label:string;session:{name:string;email:string;role:AccessRole};projects:ProjectFixture[];workspace?:ProjectWorkspaceFixture;processingJob?:ProcessingJobFixture;lens:{selectedPrdIds:string[];mode:"highlight"|"isolate"}};
const names:Record<string,string>={"safara-increment-01":"Safara Increment 01 - Fondasi Data dan Pendaftaran Jemaah","safara-increment-02":"Safara Increment 02 - Pembayaran, Dokumen, dan Kesiapan Keberangkatan","safara-increment-03":"Safara Increment 03 - Manifest, Dashboard, Laporan, dan Riwayat Aktivitas"};
const S=(id:string,understood:string,quote:string,documentId:keyof typeof names,page:number):SourceEvidence=>({id,understood,quote,documentId,documentName:names[documentId],page});
const N=(id:string,title:string,note:string,kind:WorkflowNodeFixture["kind"],prdIds:string[],understood:string,quote:string,documentId:keyof typeof names,page:number):WorkflowNodeFixture=>({id,title,note,kind,prdIds,evidence:S(id+"-evidence",understood,quote,documentId,page)});
const project:ProjectFixture={id:"safara",name:"Safara operations platform",status:"ready",prdCount:3,collaborators:4,lastActivity:"Current accepted project source of truth",isShared:false,repository:{state:"published",summary:"Operational workspace for registrations, payments, documents, and readiness.",master:{state:"published",summary:"Published work",detail:"Current accepted project source of truth."},metrics:[{value:"85",label:"resolved facts"},{value:"3",label:"PRDs"},{value:"1",label:"published version"}],action:{label:"Open project",enabled:true}}};
const W=(id:string,groupId:string,title:string,businessQuestion:string,roles:string[],expectedResult:string,prdIds:string[],relatedFactIds:string[],nodes:WorkflowNodeFixture[],evidence:SourceEvidence[]):WorkflowFixture=>({id,groupId,title,summary:"Atlas interpretation of the source-grounded workflow.",businessQuestion,roles,expectedResult,prdIds,relatedFactIds,nodes,evidence});
const R=(id:string,statement:string,prdId:keyof typeof names,page:number,workflowIds:string[],cesItemIds:string[],understood:string):FactRowFixture=>({id,statement,prdIds:[prdId],relatedWorkflowIds:workflowIds,cesItemIds,evidence:[S(id+"-evidence",understood,statement,prdId,page)]});
const workspace:ProjectWorkspaceFixture={
 project,prds:[{id:"safara-increment-01",name:"Fondasi Data dan Pendaftaran Jemaah",increment:"PRD 1",publishedAt:"27 July 2026",pageCount:3,selectedByDefault:true},{id:"safara-increment-02",name:"Pembayaran, Dokumen, dan Kesiapan Keberangkatan",increment:"PRD 2",publishedAt:"27 July 2026",pageCount:4},{id:"safara-increment-03",name:"Manifest, Dashboard, Laporan, dan Riwayat Aktivitas",increment:"PRD 3",publishedAt:"27 July 2026",pageCount:4}],
 memberships:[{id:"nadia",name:"Nadia Hartono",email:"nadia@example.com",role:"owner",status:"active"},{id:"raka",name:"Raka Pratama",email:"raka@example.com",role:"editor",status:"active"},{id:"sari",name:"Sari Utami",email:"sari@example.com",role:"viewer",status:"active"},{id:"maya",name:"Maya Santoso",email:"maya@example.com",role:"viewer",status:"invited"}],
 workflowGroups:[
  {id:"foundation",order:"01",title:"Menyiapkan paket dan keberangkatan",summary:"Source steps establish packages and schedules before registration.",expectedResult:"A departure is ready to receive registrations.",roles:["Owner/Admin"],workflowIds:["packages","schedules"],prdIds:["safara-increment-01"]},
  {id:"enrollment",order:"02",title:"Mendaftarkan jemaah",summary:"Source steps establish pilgrim data, registration, quota, and agreed price.",expectedResult:"A valid registration and agreement are recorded.",roles:["Owner/Admin"],workflowIds:["pilgrim-data","registration"],prdIds:["safara-increment-01"]},
  {id:"requirements",order:"03",title:"Memeriksa pembayaran dan persyaratan perjalanan",summary:"Source steps cover payment, documents, and travel status.",expectedResult:"Requirements are explainable.",roles:["Owner/Admin","Finance","Operations"],workflowIds:["payments","documents","travel-status"],prdIds:["safara-increment-02"]},
  {id:"readiness",order:"04",title:"Menentukan kesiapan keberangkatan",summary:"All six stated conditions determine readiness.",expectedResult:"Siap or Terhambat includes every blocker.",roles:["Owner/Admin","Operations"],workflowIds:["readiness"],prdIds:["safara-increment-02"]},
  {id:"finalization",order:"05",title:"Memfinalisasi keberangkatan",summary:"Ready-only pilgrims form a stable final manifest.",expectedResult:"A final manifest is stable and exportable.",roles:["Operations"],workflowIds:["manifest"],prdIds:["safara-increment-03"]},
  {id:"oversight",order:"S",title:"Pengawasan operasional",summary:"Reporting and activity history support the operating model.",expectedResult:"Operations are inspectable and traceable.",roles:["Owner/Admin","Finance","Operations"],workflowIds:["reporting","activity-history"],prdIds:["safara-increment-03"],support:true}
 ],
 workflows:[
  W("packages","foundation","Mengelola paket umrah","Bagaimana paket umrah dikelola?",["Owner/Admin"],"A package supports one or more schedules.",["safara-increment-01"],["fact-scope","fact-roles"],[N("package-manage","Kelola paket","Create, view, update, or deactivate.","activity",["safara-increment-01"],"Atlas reads this as package maintenance.","Admin dapat membuat, melihat, mengubah, dan menonaktifkan paket umrah.","safara-increment-01",2),N("package-fields","Isi informasi paket","Capture the stated minimum fields.","outcome",["safara-increment-01"],"Atlas treats these as package attributes.","Informasi paket minimal mencakup nama paket, durasi, harga dasar, deskripsi, dan status aktif.","safara-increment-01",2)],[S("packages-evidence","Atlas groups package statements into one workflow.","Setiap paket dapat memiliki satu atau lebih jadwal keberangkatan.","safara-increment-01",2)]),
  W("schedules","foundation","Membuat jadwal keberangkatan","Bagaimana keberangkatan dibuka untuk pendaftaran?",["Owner/Admin"],"A schedule exposes registered count and remaining quota.",["safara-increment-01"],["fact-scope","fact-constraints"],[N("schedule-create","Buat jadwal untuk paket","Associate schedule with package.","activity",["safara-increment-01"],"Atlas reads schedule as a package's operational instance.","Setiap paket dapat memiliki satu atau lebih jadwal keberangkatan.","safara-increment-01",2),N("schedule-quota","Tampilkan kuota","Show registration count and remaining quota.","decision",["safara-increment-01"],"Atlas reads quota as a registration boundary.","Aplikasi menampilkan jumlah jemaah terdaftar dan sisa kuota.","safara-increment-01",2)],[S("schedules-evidence","Atlas groups schedule and capacity statements.","Pendaftaran baru tidak dapat dilakukan apabila jadwal sudah ditutup atau kuota sudah penuh.","safara-increment-01",2)]),
  W("pilgrim-data","enrollment","Mengelola data jemaah","Bagaimana data jemaah dipelihara?",["Owner/Admin"],"A uniquely identified pilgrim record supports registration.",["safara-increment-01"],["fact-protection"],[N("pilgrim-manage","Kelola data jemaah","Add, view, update, search, or deactivate.","activity",["safara-increment-01"],"Atlas reads this as source-record maintenance.","Admin dapat menambah, melihat, mengubah, mencari, dan menonaktifkan data jemaah.","safara-increment-01",2),N("pilgrim-duplicate","Periksa identitas ganda","Warn about an existing NIK or passport.","warning",["safara-increment-01"],"Atlas treats this as a data-quality guard.","Aplikasi harus memberikan peringatan apabila NIK atau nomor paspor sudah digunakan oleh jemaah lain.","safara-increment-01",2)],[S("pilgrim-evidence","Atlas keeps privacy with the pilgrim record.","Informasi jemaah hanya boleh dilihat oleh pengguna yang berkepentingan.","safara-increment-01",2)]),
  W("registration","enrollment","Mendaftarkan jemaah ke keberangkatan","Bagaimana jemaah didaftarkan?",["Owner/Admin"],"A unique active registration keeps the agreed price.",["safara-increment-01"],["fact-constraints","fact-commitments"],[N("registration-select","Pilih jemaah dan jadwal","Use an open schedule.","activity",["safara-increment-01"],"Atlas places selection before registration guards.","Admin dapat memilih jemaah dan mendaftarkannya ke jadwal keberangkatan yang masih terbuka.","safara-increment-01",2),N("registration-guard","Periksa pendaftaran aktif","Prevent duplicate active registration.","decision",["safara-increment-01"],"Atlas reads this as a registration guard.","Satu jemaah dapat memiliki beberapa riwayat pendaftaran, tetapi tidak boleh memiliki dua pendaftaran aktif pada keberangkatan yang sama.","safara-increment-01",2),N("registration-price","Simpan harga yang disepakati","Keep fixed price reference.","outcome",["safara-increment-01"],"Atlas reads this as a durable commitment.","Harga yang berlaku saat pendaftaran disimpan sebagai harga pendaftaran yang disepakati dan menjadi nilai acuan tetap untuk pendaftaran tersebut.","safara-increment-01",2)],[S("registration-evidence","Atlas groups selection, guard, agreement, and history.","Pendaftaran dapat dibatalkan dengan alasan yang tercatat, tetapi riwayatnya tetap dapat dilihat.","safara-increment-01",2)]),
  W("payments","requirements","Mencatat dan memeriksa pembayaran","Bagaimana pembayaran memengaruhi sisa tagihan?",["Finance","Owner/Admin"],"Only accepted payment reduces remaining payment.",["safara-increment-02"],["fact-roles","fact-constraints","fact-commitments"],[N("payment-record","Catat pembayaran","Capture stated payment details and evidence.","activity",["safara-increment-02"],"Atlas reads this as a payment claim before its effect.","Finance dapat mencatat pembayaran dengan informasi tanggal, nominal, cara pembayaran, nomor referensi, catatan, dan bukti pembayaran.","safara-increment-02",2),N("payment-review","Terima atau tolak pembayaran","Finance reviews the evidence.","decision",["safara-increment-02"],"Atlas identifies Finance and accepted status as the transition.","Finance dapat mengubahnya menjadi Diterima atau Ditolak.","safara-increment-02",2),N("payment-balance","Hitung sisa pembayaran","Use accepted value only.","outcome",["safara-increment-02"],"Atlas reads this as a derived result.","Sisa Pembayaran = Total Tagihan - Total Pembayaran Diterima","safara-increment-02",2)],[S("payments-evidence","Atlas groups payment capture, review, and calculation.","Hanya pembayaran berstatus Diterima yang mengurangi sisa pembayaran.","safara-increment-02",2)]),
  W("documents","requirements","Memeriksa dokumen jemaah","Bagaimana dokumen jemaah menjadi valid?",["Operations","Owner/Admin"],"Documents have status, confidentiality, and history.",["safara-increment-02"],["fact-roles","fact-constraints","fact-protection"],[N("document-list","Lengkapi daftar dokumen","Use the stated initial list.","activity",["safara-increment-02"],"Atlas reads this as the requirement set.","Daftar awal mencakup KTP, KK, paspor, pas foto, dan dokumen vaksin atau kesehatan.","safara-increment-02",3),N("document-review","Periksa dokumen","Rejected documents require reasons.","decision",["safara-increment-02"],"Atlas reads review as actionable assessment.","Dokumen yang ditolak wajib memiliki alasan agar dapat diperbaiki.","safara-increment-02",3),N("document-history","Pertahankan riwayat","Old documents and reviews stay visible.","outcome",["safara-increment-02"],"Atlas treats this as historic evidence.","Dokumen lama dan hasil pemeriksaan sebelumnya tetap dapat dilihat sebagai riwayat.","safara-increment-02",3)],[S("documents-evidence","Atlas keeps confidentiality with document handling.","Dokumen jemaah bersifat rahasia dan hanya dapat dilihat oleh pengguna yang memiliki kewenangan.","safara-increment-02",3)]),
  W("travel-status","requirements","Memperbarui status perjalanan","Bagaimana kondisi perjalanan diperbarui?",["Operations","Owner/Admin"],"Travel changes immediately affect readiness.",["safara-increment-02"],["fact-roles","fact-constraints"],[N("travel-update","Perbarui status perjalanan","Update passport, visa, insurance, and ticket.","activity",["safara-increment-02"],"Atlas reads these as named readiness inputs.","Operations memperbarui status paspor, visa, asuransi, dan tiket.","safara-increment-02",2),N("travel-impact","Perbarui kesiapan","Changes affect displayed readiness.","outcome",["safara-increment-02"],"Atlas reads this as a current-state relationship.","Setiap perubahan pembayaran, dokumen, paspor, visa, asuransi, atau tiket harus langsung memengaruhi status kesiapan yang ditampilkan.","safara-increment-02",3)],[S("travel-evidence","Atlas groups statements as travel-status maintenance.","Operations dapat melihat data jemaah, memeriksa dokumen, memperbarui status paspor, visa, asuransi, dan tiket, serta memantau kesiapan.","safara-increment-02",2)]),
  W("readiness","readiness","Menentukan status Siap atau Terhambat","Kapan jemaah berstatus Siap atau Terhambat?",["Operations","Owner/Admin"],"Readiness is complete and explainable.",["safara-increment-02"],["fact-constraints","fact-outputs"],[N("readiness-inputs","Baca enam kondisi","Payment, documents, passport, visa, insurance, and ticket.","activity",["safara-increment-02"],"Atlas reads readiness over six named parts.","Kesiapan jemaah ditentukan dari enam bagian: Pembayaran. Dokumen wajib. Paspor. Visa. Asuransi. Tiket.","safara-increment-02",3),N("readiness-check","Periksa seluruh syarat","All must be met for Siap.","decision",["safara-increment-02"],"Atlas reads this as an all-conditions decision.","Jemaah berstatus Siap hanya apabila: Sisa pembayaran sudah nol. Seluruh dokumen wajib berstatus Valid. Paspor tersedia dan masih memenuhi ketentuan perjalanan. Visa berstatus Disetujui. Asuransi berstatus Terbit. Tiket berstatus Terbit.","safara-increment-02",3),N("readiness-blockers","Tampilkan seluruh penghambat","Show every reason, not one.","warning",["safara-increment-02"],"Atlas retains all blockers.","Apabila salah satu syarat belum terpenuhi, status jemaah menjadi Terhambat. Aplikasi harus menampilkan seluruh alasan penghambat, bukan hanya satu alasan.","safara-increment-02",3)],[S("readiness-evidence","Atlas groups conditions and blocker display into readiness.","Semua alasan yang menghambat kesiapan harus ditampilkan bersamaan.","safara-increment-02",3)]),
  W("manifest","finalization","Membuat manifest final","Bagaimana manifest menjadi final?",["Operations"],"A final PDF or Excel manifest is stable and attributable.",["safara-increment-03"],["fact-constraints","fact-outputs","fact-protection"],[N("manifest-candidates","Lihat calon jemaah","Start from departure candidates.","activity",["safara-increment-03"],"Atlas reads manifest as departure-specific.","Operations dapat melihat daftar calon jemaah untuk setiap keberangkatan.","safara-increment-03",2),N("manifest-ready","Pilih hanya jemaah Siap","Terhambat cannot be included.","decision",["safara-increment-03"],"Atlas reads readiness as the eligibility gate.","Hanya jemaah berstatus Siap yang dapat dimasukkan ke manifest final.","safara-increment-03",2),N("manifest-finalize","Finalisasi dan unduh","Final content is stable and exportable.","outcome",["safara-increment-03"],"Atlas reads it as a snapshot, not live list.","Setelah difinalisasi, isi manifest tidak berubah otomatis walaupun data jemaah kemudian diperbarui.","safara-increment-03",2)],[S("manifest-evidence","Atlas groups eligibility, finalization, attribution, and export.","Aplikasi mencatat siapa yang memfinalisasi manifest dan kapan dilakukan.","safara-increment-03",2)]),
  W("reporting","oversight","Melihat dashboard dan laporan","Bagaimana operasi dipantau dan dilaporkan?",["Owner/Admin","Finance","Operations"],"Operational information is dashboarded and downloadable.",["safara-increment-03"],["fact-outputs"],[N("report-dashboard","Lihat ringkasan dashboard","View stated counts and totals.","activity",["safara-increment-03"],"Atlas reads this as compact operating projection.","Dashboard minimum menampilkan: Jumlah jemaah aktif. Keberangkatan terdekat. Jumlah kuota terpakai dan tersisa. Total pembayaran yang sudah diterima. Total sisa pembayaran. Jumlah jemaah Siap dan Terhambat. Jumlah dokumen yang belum ada, ditolak, atau kedaluwarsa.","safara-increment-03",2),N("report-filter","Saring dan unduh laporan","Filter and download reports.","outcome",["safara-increment-03"],"Atlas reads this as report-output contract.","Laporan dapat disaring berdasarkan periode, paket, keberangkatan, status pembayaran, dan status kesiapan.","safara-increment-03",2)],[S("reporting-evidence","Atlas keeps reporting as supporting oversight.","Laporan dapat diunduh dalam format Excel, sedangkan manifest tersedia dalam PDF dan Excel.","safara-increment-03",2)]),
  W("activity-history","oversight","Meninjau riwayat aktivitas","Bagaimana tindakan penting dapat ditelusuri?",["Owner/Admin","Finance","Operations"],"Material actions and history remain traceable.",["safara-increment-03"],["fact-protection","fact-commitments"],[N("history-record","Simpan tindakan penting","Track listed operational actions.","activity",["safara-increment-03"],"Atlas reads history as accountability support.","Riwayat minimum mencakup perubahan data jemaah, pendaftaran, pemeriksaan pembayaran, pemeriksaan dokumen, perubahan status perjalanan, dan finalisasi manifest.","safara-increment-03",3),N("history-details","Tampilkan jejak perubahan","Show user, time, changed data, and summary.","outcome",["safara-increment-03"],"Atlas reads these as minimum history fields.","Riwayat menampilkan pengguna yang melakukan tindakan, waktu, data yang diubah, dan ringkasan perubahan.","safara-increment-03",3)],[S("history-evidence","Atlas treats this as retained evidence across workflows.","Data transaksi dan riwayat yang sudah pernah digunakan tidak boleh hilang hanya karena data dinonaktifkan atau dibatalkan.","safara-increment-03",3)])
 ],
 facts:[
  {id:"fact-scope",number:"01",title:"Scope",summary:"The accumulated model starts with enrollment, adds readiness, and completes finalization and oversight.",prdIds:["safara-increment-01","safara-increment-02","safara-increment-03"],rows:[R("fact-scope-foundation","Satu perusahaan dan satu cabang; paket, keberangkatan, data jemaah, pendaftaran, dan kuota.","safara-increment-01",1,["packages","schedules","pilgrim-data","registration"],["ces-scope-model"],"Atlas treats this as the first increment scope."),R("fact-scope-readiness","Menambahkan tagihan dan pembayaran, dokumen jemaah, status perjalanan, serta kesiapan keberangkatan.","safara-increment-02",1,["payments","documents","travel-status","readiness"],["ces-scope-model","ces-readiness-conditions"],"Atlas treats this as the second increment scope."),R("fact-scope-finalization","Menambahkan manifest keberangkatan, dashboard, laporan, riwayat aktivitas, serta penerimaan akhir sistem.","safara-increment-03",1,["manifest","reporting","activity-history"],["ces-scope-model"],"Atlas treats this as the third increment scope.")]},
  {id:"fact-roles",number:"02",title:"People and responsibilities",summary:"The PRDs state broad ownership and named financial and operational roles.",prdIds:["safara-increment-02"],rows:[R("fact-role-owner","Owner/Admin dapat melihat dan mengelola seluruh data yang telah tersedia sampai increment ini, termasuk pendaftaran, pembayaran, dokumen, dan kesiapan.","safara-increment-02",2,["payments","documents","travel-status","readiness"],["ces-role-authority"],"Atlas reads this as broad Owner/Admin responsibility."),R("fact-role-finance","Finance dapat melihat tagihan jemaah, mencatat pembayaran, memeriksa bukti pembayaran, menerima atau menolak pembayaran, serta melihat informasi pembayaran.","safara-increment-02",2,["payments"],["ces-role-authority","ces-payment-review"],"Atlas reads Finance as the payment role."),R("fact-role-operations","Operations dapat melihat data jemaah, memeriksa dokumen, memperbarui status paspor, visa, asuransi, dan tiket, serta memantau kesiapan.","safara-increment-02",2,["documents","travel-status","readiness","manifest"],["ces-role-authority"],"Atlas reads Operations as the travel-readiness role.")]},
  {id:"fact-constraints",number:"03",title:"Constraints",summary:"Source rules govern capacity, payment acceptance, readiness, and manifest eligibility.",prdIds:["safara-increment-01","safara-increment-02","safara-increment-03"],rows:[R("fact-registration-quota","Pendaftaran baru tidak dapat dilakukan apabila jadwal sudah ditutup atau kuota sudah penuh.","safara-increment-01",2,["schedules","registration"],["ces-capacity"],"Atlas reads this as the capacity guard."),R("fact-payment-acceptance","Hanya pembayaran berstatus Diterima yang mengurangi sisa pembayaran.","safara-increment-02",2,["payments","readiness"],["ces-payment-review"],"Atlas reads accepted status as financial transition."),R("fact-readiness-conditions","Jemaah berstatus Siap hanya apabila: Sisa pembayaran sudah nol. Seluruh dokumen wajib berstatus Valid. Paspor tersedia dan masih memenuhi ketentuan perjalanan. Visa berstatus Disetujui. Asuransi berstatus Terbit. Tiket berstatus Terbit.","safara-increment-02",3,["readiness","manifest"],["ces-readiness-conditions"],"Atlas reads this as the complete readiness rule."),R("fact-manifest-eligibility","Jemaah Terhambat tidak boleh masuk ke manifest final.","safara-increment-03",3,["readiness","manifest"],["ces-manifest-eligibility"],"Atlas reads this as final-manifest exclusion.")]},
  {id:"fact-protection",number:"04",title:"Information protection",summary:"Source statements require role-appropriate visibility, confidentiality, and retained history.",prdIds:["safara-increment-01","safara-increment-02","safara-increment-03"],rows:[R("fact-private-information","Informasi jemaah hanya boleh dilihat oleh pengguna yang berkepentingan.","safara-increment-01",2,["pilgrim-data","documents"],["ces-information-access"],"Atlas reads this as access boundary."),R("fact-document-confidentiality","Dokumen jemaah bersifat rahasia dan hanya dapat dilihat oleh pengguna yang memiliki kewenangan.","safara-increment-02",3,["documents"],["ces-information-access","ces-evidence-retention"],"Atlas reads this as confidentiality rule."),R("fact-history-retention","Data transaksi dan riwayat yang sudah pernah digunakan tidak boleh hilang hanya karena data dinonaktifkan atau dibatalkan.","safara-increment-03",3,["payments","documents","activity-history"],["ces-evidence-retention"],"Atlas reads this as retained-history requirement.")]},
  {id:"fact-outputs",number:"05",title:"Outputs",summary:"The model produces readiness, final manifest, reports, and activity history.",prdIds:["safara-increment-02","safara-increment-03"],rows:[R("fact-readiness-output","Aplikasi menampilkan apakah jemaah sudah Siap atau masih Terhambat, beserta seluruh alasan penghambat.","safara-increment-02",2,["readiness"],["ces-readiness-conditions"],"Atlas reads this as explainable readiness output."),R("fact-manifest-output","Manifest dapat diunduh dalam format PDF dan Excel.","safara-increment-03",2,["manifest"],["ces-manifest-snapshot"],"Atlas reads this as manifest handover."),R("fact-report-output","Laporan dapat diunduh dalam format Excel, sedangkan manifest tersedia dalam PDF dan Excel.","safara-increment-03",2,["reporting","manifest"],["ces-scope-model"],"Atlas reads this as stated output format.")]},
  {id:"fact-commitments",number:"06",title:"Commitments",summary:"Agreed price and prior records survive later changes.",prdIds:["safara-increment-01","safara-increment-03"],rows:[R("fact-agreed-price","Perubahan harga paket setelah pendaftaran tidak boleh mengubah harga pendaftaran yang sudah disepakati.","safara-increment-01",2,["registration","payments"],["ces-agreed-price"],"Atlas reads the price as a durable agreement."),R("fact-cancellation-history","Pembatalan atau penonaktifan data tidak boleh menghilangkan riwayat sebelumnya.","safara-increment-03",3,["registration","activity-history"],["ces-evidence-retention"],"Atlas reads the repeated rule as a durable commitment.")]}
 ],
 changes:[
  {id:"change-01-foundation",kind:"established",title:"Fondasi data dan pendaftaran",summary:"Established package, schedule, pilgrim-data, registration, and quota work.",prdId:"safara-increment-01",destination:{type:"workflow",targetId:"registration",label:"Main Workflow / Mendaftarkan jemaah ke keberangkatan"},evidence:[S("change-01-foundation-evidence","Atlas identifies the first accumulated model.","Dokumen ini menetapkan fondasi operasional pertama Safara.","safara-increment-01",1)]},
  {id:"change-01-price",kind:"established",title:"Harga pendaftaran yang disepakati",summary:"Established a durable registration-price commitment.",prdId:"safara-increment-01",destination:{type:"fact",targetId:"fact-commitments",label:"Project Facts / Commitments"},evidence:[S("change-01-price-evidence","Atlas records durable commercial agreement.","Perubahan harga paket setelah pendaftaran tidak boleh mengubah harga pendaftaran yang sudah disepakati.","safara-increment-01",2)]},
  {id:"change-02-scope",kind:"expanded",title:"Pembayaran, dokumen, dan kesiapan",summary:"Expanded the model with financial, document, travel-status, and readiness workflows.",prdId:"safara-increment-02",destination:{type:"workflow",targetId:"readiness",label:"Main Workflow / Menentukan status Siap atau Terhambat"},evidence:[S("change-02-scope-evidence","Atlas identifies extension, not replacement.","Dokumen ini merupakan penambahan terhadap Increment 01.","safara-increment-02",1)]},
  {id:"change-02-roles",kind:"clarified",title:"Tanggung jawab Finance dan Operations",summary:"Clarified named payment and travel-readiness responsibility.",prdId:"safara-increment-02",destination:{type:"fact",targetId:"fact-roles",label:"Project Facts / People and responsibilities"},evidence:[S("change-02-roles-evidence","Atlas records responsibility clarification.","Setiap pengguna hanya boleh melihat dan menjalankan pekerjaan yang sesuai dengan tanggung jawabnya.","safara-increment-02",2)]},
  {id:"change-02-evidence-gap",kind:"unresolved",title:"Masa simpan bukti dan dokumen",summary:"History visibility is stated, but no retention period or disposition decision is stated.",prdId:"safara-increment-02",destination:{type:"ces",targetId:"ces-evidence-retention",label:"CES Result / Retained operational evidence"},evidence:[S("change-02-evidence-gap-evidence","Atlas does not invent an unstated retention period.","Dokumen lama dan hasil pemeriksaan sebelumnya tetap dapat dilihat sebagai riwayat.","safara-increment-02",3)]},
  {id:"change-03-finalization",kind:"expanded",title:"Manifest final dan pengawasan",summary:"Expanded into manifest finalization, reporting, and activity history.",prdId:"safara-increment-03",destination:{type:"workflow",targetId:"manifest",label:"Main Workflow / Membuat manifest final"},evidence:[S("change-03-finalization-evidence","Atlas identifies final operational extension.","Increment ini menyelesaikan alur operasional sampai manifest dan menyediakan laporan serta riwayat aktivitas.","safara-increment-03",1)]},
  {id:"change-03-manifest",kind:"established",title:"Snapshot manifest final",summary:"Established stable, ready-only, exportable manifest output.",prdId:"safara-increment-03",destination:{type:"fact",targetId:"fact-outputs",label:"Project Facts / Outputs"},evidence:[S("change-03-manifest-evidence","Atlas records snapshot rather than live list.","Setelah difinalisasi, isi manifest tidak berubah otomatis walaupun data jemaah kemudian diperbarui.","safara-increment-03",2)]},
  {id:"change-03-history",kind:"expanded",title:"Riwayat tindakan penting",summary:"Expanded accountable history across the operating model.",prdId:"safara-increment-03",destination:{type:"workflow",targetId:"activity-history",label:"Main Workflow / Meninjau riwayat aktivitas"},evidence:[S("change-03-history-evidence","Atlas identifies cross-workflow accountability support.","Aplikasi menyimpan riwayat tindakan penting dari seluruh alur.","safara-increment-03",2)]}
 ],
 sourceAccounting:[
  {id:"statement-01-quota",prdId:"safara-increment-01",statement:"Pendaftaran baru tidak dapat dilakukan apabila jadwal sudah ditutup atau kuota sudah penuh.",destination:{type:"workflow",targetId:"registration",label:"Main Workflow / Mendaftarkan jemaah ke keberangkatan"},evidence:[S("statement-01-quota-evidence","Atlas places this in registration guard.","Pendaftaran baru tidak dapat dilakukan apabila jadwal sudah ditutup atau kuota sudah penuh.","safara-increment-01",2)]},
  {id:"statement-02-payment",prdId:"safara-increment-02",statement:"Hanya pembayaran berstatus Diterima yang mengurangi sisa pembayaran.",destination:{type:"workflow",targetId:"payments",label:"Main Workflow / Mencatat dan memeriksa pembayaran"},evidence:[S("statement-02-payment-evidence","Atlas places this in payment review.","Hanya pembayaran berstatus Diterima yang mengurangi sisa pembayaran.","safara-increment-02",2)]},
  {id:"statement-02-retention",prdId:"safara-increment-02",statement:"Dokumen lama dan hasil pemeriksaan sebelumnya tetap dapat dilihat sebagai riwayat.",destination:{type:"ces",targetId:"ces-evidence-retention",label:"CES Result / Retained operational evidence"},evidence:[S("statement-02-retention-evidence","Atlas links the history requirement to CES lifecycle question.","Dokumen lama dan hasil pemeriksaan sebelumnya tetap dapat dilihat sebagai riwayat.","safara-increment-02",3)]},
  {id:"statement-03-manifest",prdId:"safara-increment-03",statement:"Jemaah Terhambat tidak boleh masuk ke manifest final.",destination:{type:"workflow",targetId:"manifest",label:"Main Workflow / Membuat manifest final"},evidence:[S("statement-03-manifest-evidence","Atlas places this in eligibility decision.","Jemaah Terhambat tidak boleh masuk ke manifest final.","safara-increment-03",3)]}
 ],
 cesItems:[
  {id:"ces-scope-model",policyId:"CES-SCP-01",policy:"Operational scope traceability",rule:"Each stated scope remains traceable to its source increment.",conclusion:"The three increments form a source-traceable accumulated model.",obligation:"Account for source increment of each operational scope.",sourcePrdIds:["safara-increment-01","safara-increment-02","safara-increment-03"],linkedFactIds:["fact-scope","fact-outputs"],linkedFactRowIds:["fact-scope-foundation","fact-scope-readiness","fact-scope-finalization","fact-report-output"],relatedWorkflowIds:["packages","readiness","manifest","reporting"],concern:"Later capability could lose increment context.",capabilityNeed:"Retain source-increment provenance for accumulated scope.",coverage:"covered",destination:{type:"fact",targetId:"fact-scope",label:"Project Facts / Scope"},evidence:[S("ces-scope-evidence","CES grounds this in explicit scopes.","Menambahkan manifest keberangkatan, dashboard, laporan, riwayat aktivitas, serta penerimaan akhir sistem.","safara-increment-03",1)]},
  {id:"ces-role-authority",policyId:"CES-ACC-02",policy:"Role-appropriate access",rule:"Users only perform work within stated responsibility.",conclusion:"Named Finance and Operations responsibilities are explicit.",obligation:"Account for role-specific visibility and permitted work.",sourcePrdIds:["safara-increment-02"],linkedFactIds:["fact-roles"],linkedFactRowIds:["fact-role-owner","fact-role-finance","fact-role-operations"],relatedWorkflowIds:["payments","documents","travel-status","readiness"],concern:"Broad access could expose inappropriate data or actions.",capabilityNeed:"Make permitted work and visibility enforceable and reviewable.",coverage:"covered",destination:{type:"fact",targetId:"fact-roles",label:"Project Facts / People and responsibilities"},evidence:[S("ces-roles-evidence","CES grounds this in source responsibility boundary.","Setiap pengguna hanya boleh melihat dan menjalankan pekerjaan yang sesuai dengan tanggung jawabnya.","safara-increment-02",2)]},
  {id:"ces-capacity",policyId:"CES-CAP-03",policy:"Capacity boundary",rule:"Registration must not pass a closed or full departure boundary.",conclusion:"The registration guard covers the capacity boundary.",obligation:"Account for open status and quota before registration.",sourcePrdIds:["safara-increment-01"],linkedFactIds:["fact-constraints"],linkedFactRowIds:["fact-registration-quota"],relatedWorkflowIds:["schedules","registration"],concern:"Registration could exceed capacity.",capabilityNeed:"Evaluate availability and quota before registration.",coverage:"covered",destination:{type:"workflow",targetId:"registration",label:"Main Workflow / Mendaftarkan jemaah ke keberangkatan"},evidence:[S("ces-capacity-evidence","CES grounds this in registration prohibition.","Pendaftaran baru tidak dapat dilakukan apabila jadwal sudah ditutup atau kuota sudah penuh.","safara-increment-01",2)]},
  {id:"ces-payment-review",policyId:"CES-FIN-04",policy:"Accepted-payment control",rule:"Only accepted payment may alter remaining payment.",conclusion:"The source covers the stated financial transition.",obligation:"Account for evidence, review, rejection reason, and accepted-value calculation.",sourcePrdIds:["safara-increment-02"],linkedFactIds:["fact-roles","fact-constraints"],linkedFactRowIds:["fact-role-finance","fact-payment-acceptance"],relatedWorkflowIds:["payments","readiness"],concern:"Pending or rejected payment could reduce balance.",capabilityNeed:"Distinguish review states and calculate from accepted payments.",coverage:"covered",destination:{type:"workflow",targetId:"payments",label:"Main Workflow / Mencatat dan memeriksa pembayaran"},evidence:[S("ces-payment-evidence","CES grounds this in accepted-payment condition.","Hanya pembayaran berstatus Diterima yang mengurangi sisa pembayaran.","safara-increment-02",2)]},
  {id:"ces-readiness-conditions",policyId:"CES-OPS-05",policy:"Complete readiness assessment",rule:"Readiness considers every stated condition and reveals every blocker.",conclusion:"The source defines six inputs and complete blocker display.",obligation:"Account for payment, documents, passport, visa, insurance, and ticket together.",sourcePrdIds:["safara-increment-02"],linkedFactIds:["fact-scope","fact-constraints","fact-outputs"],linkedFactRowIds:["fact-scope-readiness","fact-readiness-conditions","fact-readiness-output"],relatedWorkflowIds:["payments","documents","travel-status","readiness","manifest"],concern:"A partial reading could falsely show ready.",capabilityNeed:"Evaluate all six conditions and show every blocker.",coverage:"covered",destination:{type:"workflow",targetId:"readiness",label:"Main Workflow / Menentukan status Siap atau Terhambat"},evidence:[S("ces-readiness-evidence","CES grounds this in complete blocker display.","Apabila salah satu syarat belum terpenuhi, status jemaah menjadi Terhambat. Aplikasi harus menampilkan seluruh alasan penghambat, bukan hanya satu alasan.","safara-increment-02",3)]},
  {id:"ces-manifest-eligibility",policyId:"CES-OPS-06",policy:"Final-manifest eligibility",rule:"A blocked pilgrim must not enter final manifest.",conclusion:"Source gives a direct eligibility exclusion.",obligation:"Account for readiness in manifest selection.",sourcePrdIds:["safara-increment-03"],linkedFactIds:["fact-constraints"],linkedFactRowIds:["fact-manifest-eligibility"],relatedWorkflowIds:["readiness","manifest"],concern:"An ineligible pilgrim could enter final output.",capabilityNeed:"Prevent Terhambat inclusion.",coverage:"covered",destination:{type:"workflow",targetId:"manifest",label:"Main Workflow / Membuat manifest final"},evidence:[S("ces-manifest-evidence","CES grounds this in direct prohibition.","Jemaah Terhambat tidak boleh masuk ke manifest final.","safara-increment-03",3)]},
  {id:"ces-information-access",policyId:"CES-PRV-07",policy:"Confidential information access",rule:"Pilgrim information and documents require authorized visibility.",conclusion:"The PRDs establish access boundaries but do not say how access changes are reviewed.",obligation:"Account for authorized access to pilgrim information and documents.",sourcePrdIds:["safara-increment-01","safara-increment-02"],linkedFactIds:["fact-protection"],linkedFactRowIds:["fact-private-information","fact-document-confidentiality"],relatedWorkflowIds:["pilgrim-data","documents"],concern:"Sensitive information could be viewed outside stated need.",capabilityNeed:"Make authorized access visible and controllable.",coverage:"needs-review",decision:"Confirm how authorized access is reviewed when responsibilities or access assignments change.",destination:{type:"fact",targetId:"fact-protection",label:"Project Facts / Information protection"},evidence:[S("ces-access-evidence","CES grounds review in confidentiality; review mechanism is unstated.","Dokumen jemaah bersifat rahasia dan hanya dapat dilihat oleh pengguna yang memiliki kewenangan.","safara-increment-02",3)]},
  {id:"ces-evidence-retention",policyId:"CES-RET-08",policy:"Retained operational evidence",rule:"Used records and prior reviews remain traceable after later changes.",conclusion:"History visibility is stated, but no retention period or disposal decision is stated.",obligation:"Account for retained document, transaction, and activity-history evidence.",sourcePrdIds:["safara-increment-02","safara-increment-03"],linkedFactIds:["fact-protection","fact-commitments"],linkedFactRowIds:["fact-document-confidentiality","fact-history-retention","fact-cancellation-history"],relatedWorkflowIds:["documents","payments","registration","activity-history"],concern:"History could be unavailable or retained without lifecycle decision.",capabilityNeed:"Preserve historic evidence and make its status traceable.",coverage:"unresolved",decision:"Decide retention period and disposition authority for historic evidence.",destination:{type:"unresolved",label:"Needs answer / evidence retention period and disposition"},evidence:[S("ces-retention-evidence","CES retains source history and marks lifecycle as unresolved.","Data transaksi dan riwayat yang sudah pernah digunakan tidak boleh hilang hanya karena data dinonaktifkan atau dibatalkan.","safara-increment-03",3)]},
  {id:"ces-manifest-snapshot",policyId:"CES-OUT-09",policy:"Stable handover output",rule:"Final manifest is a durable snapshot, not a live projection.",conclusion:"The stated snapshot is outside current CES baseline-review focus.",obligation:"Identify stable handover and export formats.",sourcePrdIds:["safara-increment-03"],linkedFactIds:["fact-outputs"],linkedFactRowIds:["fact-manifest-output"],relatedWorkflowIds:["manifest"],concern:"Output is already specified as stable.",capabilityNeed:"No additional CES capability need is identified.",coverage:"out-of-scope",destination:{type:"workflow",targetId:"manifest",label:"Main Workflow / Membuat manifest final"},evidence:[S("ces-snapshot-evidence","CES grounds this in non-changing manifest behavior.","Setelah difinalisasi, isi manifest tidak berubah otomatis walaupun data jemaah kemudian diperbarui.","safara-increment-03",2)]},
  {id:"ces-agreed-price",policyId:"CES-CMT-10",policy:"Preserved registration commitment",rule:"Later package-price change must not rewrite agreed registration price.",conclusion:"Source states durable registration-price commitment.",obligation:"Account for agreed price as fixed registration reference.",sourcePrdIds:["safara-increment-01"],linkedFactIds:["fact-commitments"],linkedFactRowIds:["fact-agreed-price"],relatedWorkflowIds:["registration","payments"],concern:"Package maintenance could alter historical agreement.",capabilityNeed:"Retain agreed price independently of package-price changes.",coverage:"covered",destination:{type:"fact",targetId:"fact-commitments",label:"Project Facts / Commitments"},evidence:[S("ces-price-evidence","CES grounds this in source non-change rule.","Perubahan harga paket setelah pendaftaran tidak boleh mengubah harga pendaftaran yang sudah disepakati.","safara-increment-01",2)]}
 ],
 atlasApproval:"awaiting-approval",cesApproval:"awaiting-approval"
};
const processingProject:ProjectFixture={id:"member-portal",name:"Member portal refresh",status:"processing",prdCount:5,collaborators:2,lastActivity:"Extracting project facts",isShared:true,repository:{state:"extracting",summary:"Updating the member portal from newly uploaded PRDs.",master:{state:"empty",summary:"No published work",detail:"Nothing has been published yet."},initialDraft:{processedPrds:2,totalPrds:5,progress:40},metrics:[{value:"0",label:"published facts"},{value:"5",label:"PRDs uploaded"},{value:"Waiting",label:"for extraction"}],action:{label:"Open project",enabled:false}}}; const reviewProject:ProjectFixture={id:"vendor-onboarding",name:"Vendor onboarding revamp",status:"ready",prdCount:2,collaborators:3,lastActivity:"Initial draft is ready for review",isShared:false,repository:{state:"ready-for-review",summary:"New onboarding workflow prepared from uploaded PRDs and ready to check.",master:{state:"empty",summary:"No published work",detail:"Nothing has been published yet."},initialDraft:{processedPrds:2,totalPrds:2,progress:100},metrics:[{value:"46",label:"extracted facts"},{value:"2",label:"PRDs uploaded"},{value:"Ready",label:"to review"}],action:{label:"Review workspace unavailable",enabled:false,unavailableReason:"This fixture demonstrates a completed Initial Draft. A review workspace is not available in this prototype."}}}; export const sfe002RouteProject:ProjectFixture={...reviewProject,id:"safara-project-01",name:"Safara Initial Draft",prdCount:1,lastActivity:"Initial Draft is ready for review",repository:{...reviewProject.repository,summary:"Initial Draft extraction is complete and awaiting review.",initialDraft:{processedPrds:1,totalPrds:1,progress:100},metrics:[{value:"47",label:"extracted facts"},{value:"1",label:"PRD uploaded"},{value:"Ready",label:"to review"}],action:{label:"Review Initial Draft",enabled:true}}}; const attentionProject:ProjectFixture={id:"supplier-access",name:"Supplier access update",status:"needs-attention",prdCount:1,collaborators:1,lastActivity:"One PDF needs another upload",isShared:false,repository:{state:"extracting",summary:"A protected PDF needs attention before draft extraction can finish.",master:{state:"empty",summary:"No published work",detail:"Nothing has been published yet."},initialDraft:{processedPrds:0,totalPrds:1,progress:68},metrics:[{value:"0",label:"published facts"},{value:"1",label:"PRD uploaded"},{value:"Needs attention",label:"before extraction"}],action:{label:"Open project",enabled:false}}}; const owner={name:"Nadia Hartono",email:"nadia@example.com",role:"owner"} as const;
export const projectCardStressLimits={id:48,name:80,description:280} as const;
export const projectIdPattern=/^[a-z0-9]+(?:-[a-z0-9]+)*$/;
export function createFixtureProject(request:ProjectCreateRequest,tokens:readonly string[]=["a2b3c4d5e6f7"],usedWorkspaceIds:readonly string[]=[]):CreatedFixtureProject {
 const projectId=request.projectId.toLowerCase();
 const prdCount=request.prdFiles.length;
 const prefix=projectId.replace(/[^a-z0-9]/g,"").slice(0,3);
 if(prefix.length!==3) throw new Error("Project ID needs a three-character prefix.");
 const used=new Set(usedWorkspaceIds);
 const token=tokens.find(value=>/^[a-z2-7]{12}$/.test(value)&&!used.has(`${prefix}-${value}`));
 if(!token) throw new Error("Unable to allocate a unique workspace ID.");
 const workspaceId=`${prefix}-${token}`;
 const project:ProjectFixture={
  id:projectId,name:request.projectName,status:"processing",prdCount,collaborators:1,lastActivity:"Extraction has started",isShared:false,
  repository:{state:"extracting",summary:request.projectDescription.trim()||"Atlas is extracting an Initial Draft from the submitted PRDs.",master:{state:"empty",summary:"No published work",detail:"Nothing has been published yet."},initialDraft:{processedPrds:0,totalPrds:prdCount,progress:0},metrics:[{value:"0",label:"published facts"},{value:String(prdCount),label:`PRD${prdCount===1?"":"s"} uploaded`},{value:"Waiting",label:"for extraction"}],action:{label:"Open project",enabled:false,unavailableReason:"Extraction is in progress. This project cannot be opened yet."}}
 };
 return {request:{...request,projectId},project,processingJob:{id:`job-${projectId}`,projectId,workspaceId,stage:"extracting",message:"Extracting text and structure",progress:0},masterWorkspace:{workspaceId:"master",projectId,workspaceName:"Master",status:"empty",prdFiles:[]},initialDraftWorkspace:{workspaceId,projectId,workspaceName:"Initial Draft",status:"extracting",available:false,unavailableReason:"Extraction is in progress. This workspace cannot be opened yet.",prdFiles:request.prdFiles.map(file=>({...file}))},prdRecord:{projectId,workspaceId,prdFiles:request.prdFiles.map(file=>({...file}))}};
}
export const workspaceIdPattern=/^[a-z0-9]{3}-[a-z2-7]{12}$/;
export const fixtureWorkspaceProjectInventory=["safara"] as const;
export type WorkspaceInventoryFixture={workspaceId:string;projectId:string;name:string;status:"Published"|"Review"|"Processing";prdCount:number;baseWorkspaceId?:string;headRevisionId:string;executionProvenance:string;createdBy:string;createdAt:string;modifiedBy:string;modifiedAt:string;relative:string;available:boolean;unavailableReason?:string};
export const fixtureWorkspaceInventory:readonly WorkspaceInventoryFixture[]=[
 {workspaceId:"branch-master",projectId:"safara",name:"Master",status:"Published",prdCount:5,headRevisionId:"rev-safara-master-002",executionProvenance:"codex · verified",createdBy:"Atlas",createdAt:"2026-07-27T09:14:00Z",modifiedBy:"Aditya",modifiedAt:"2026-09-11T09:48:00Z",relative:"54 min ago",available:true},
 {workspaceId:"branch-increment-003",projectId:"safara",name:"Increment 03",status:"Review",prdCount:3,baseWorkspaceId:"branch-master",headRevisionId:"rev-safara-increment-003",executionProvenance:"codex · review pending",createdBy:"Aditya",createdAt:"2026-09-09T14:32:00Z",modifiedBy:"Raka",modifiedAt:"2026-09-11T10:28:00Z",relative:"14 min ago",available:true},
 {workspaceId:"saf-a2b3c4d5e6f7",projectId:"safara",name:"Refund rules PRD-04",status:"Processing",prdCount:1,baseWorkspaceId:"branch-increment-003",headRevisionId:"pending extraction",executionProvenance:"codex · extracting",createdBy:"Aditya",createdAt:"2026-09-11T10:31:00Z",modifiedBy:"Aditya",modifiedAt:"2026-09-11T10:41:00Z",relative:"Now",available:false,unavailableReason:"Extraction is still in progress; this workspace cannot be opened yet."}
] as const;
export type FixtureRouteProjectRecord={project:ProjectFixture;masterWorkspace:{workspaceId:string;projectId:string;workspaceName:"Master";status:"empty";prdFiles:readonly PrdFileMetadata[]};initialDraftWorkspace:{workspaceId:string;projectId:string;workspaceName:"Initial Draft";status:"extracting"|"ready-for-review";available:boolean;unavailableReason?:string;prdFiles:readonly PrdFileMetadata[]};processingJob:{workspaceId:string;stage:ProcessingStage}};
// This is the persisted SFE-002 record used by the checked-in demo. Route lookup
// never keys off its label or example ID: callers may supply any modal-created record.
const persistedSfe002RouteRecord=(projectFixtureRegistry as {modalProjects?: FixtureRouteProjectRecord[]}).modalProjects?.find((record)=>record.project.id==="safara-project-01");
if(!persistedSfe002RouteRecord) throw new Error("The checked-in SFE-002 modal project fixture is required for route wiring.");
export const sfe002RouteRecord:FixtureRouteProjectRecord=persistedSfe002RouteRecord;
const routeRecords=(records:readonly FixtureRouteProjectRecord[])=>[sfe002RouteRecord,...records.filter((record)=>record.project.id!==sfe002RouteRecord.project.id)];
const routeRecordFor=(projectId:string,records:readonly FixtureRouteProjectRecord[])=>routeRecords(records).find((record)=>record.project.id===projectId);
const inventoryForRecord=(record:FixtureRouteProjectRecord):WorkspaceInventoryFixture[]=>[
 {workspaceId:record.masterWorkspace.workspaceId,projectId:record.project.id,name:"Master",status:"Published",prdCount:0,headRevisionId:`${record.initialDraftWorkspace.workspaceId}-master-empty`,executionProvenance:"codex · verified",createdBy:"Atlas",createdAt:"2026-09-13T00:00:00Z",modifiedBy:"Atlas",modifiedAt:"2026-09-13T00:00:00Z",relative:"Ready",available:true},
 {workspaceId:record.initialDraftWorkspace.workspaceId,projectId:record.project.id,name:"Initial Draft",status:record.initialDraftWorkspace.status==="ready-for-review"?"Review":"Processing",prdCount:record.initialDraftWorkspace.prdFiles.length,baseWorkspaceId:record.masterWorkspace.workspaceId,headRevisionId:record.initialDraftWorkspace.status==="ready-for-review"?`candidate-${record.initialDraftWorkspace.workspaceId}`:"pending extraction",executionProvenance:record.initialDraftWorkspace.status==="ready-for-review"?"codex · extraction complete":"codex · extracting",createdBy:"Atlas",createdAt:"2026-09-13T00:00:00Z",modifiedBy:"Atlas",modifiedAt:"2026-09-13T00:00:00Z",relative:record.initialDraftWorkspace.status==="ready-for-review"?"Ready for review":"Extracting",available:record.initialDraftWorkspace.available,unavailableReason:record.initialDraftWorkspace.available?undefined:record.initialDraftWorkspace.unavailableReason}
];
export const sfe002WorkspaceInventory=inventoryForRecord(sfe002RouteRecord);
export function resolveFixtureWorkspaceInventory(projectId:string,records:readonly FixtureRouteProjectRecord[]=[]){const record=routeRecordFor(projectId,records);return record?inventoryForRecord(record):fixtureWorkspaceInventory.filter((workspace)=>workspace.projectId===projectId);}
export function resolveFixtureWorkspaceRoute(projectId:string,workspaceId?:string,records:readonly FixtureRouteProjectRecord[]=[]){const inventory=resolveFixtureWorkspaceInventory(projectId,records);const defaultWorkspace=inventory.find((workspace)=>workspace.name==="Initial Draft"&&workspace.available)??inventory.find((workspace)=>workspace.workspaceId==="branch-increment-003"&&workspace.available)??inventory.find((workspace)=>workspace.available);const requested=workspaceId?inventory.find((workspace)=>workspace.workspaceId===workspaceId):undefined;return {selectedWorkspace:requested?.available?requested:defaultWorkspace,unavailableWorkspace:requested&&!requested.available?requested:undefined};}
export function createFixtureWorkspace(request:WorkspaceCreationRequest,bases:readonly WorkspaceCreationBase[],tokens:readonly string[]=["a2b3c4d5e6f7"],projectInventory:readonly string[]=fixtureWorkspaceProjectInventory):CreatedWorkspaceRequest {
 if(!projectInventory.includes(request.projectId)) throw new Error("Unknown project."); if(!request.workspaceName.trim()) throw new Error("Workspace name is required."); if(!request.prdFiles.length) throw new Error("At least one PDF is required."); if(request.prdFiles.some(file=>file.type!=="application/pdf")) throw new Error("Workspace PRDs must be PDFs.");
 const base=bases.find(item=>item.workspaceId===request.baseWorkspaceId&&item.projectId===request.projectId); if(!base) throw new Error("Unknown base workspace for project.");
 let cursor:WorkspaceCreationBase|undefined=base, rooted=false, steps=0; while(cursor&&steps++<=bases.length){if(!cursor.baseWorkspaceId){rooted=cursor.workspaceId==="master"||cursor.workspaceId.endsWith("-master");break;}cursor=bases.find(item=>item.workspaceId===cursor!.baseWorkspaceId&&item.projectId===request.projectId);} if(!rooted) throw new Error("Base workspace must be Master-rooted.");
 const prefix=request.projectId.toLowerCase().replace(/[^a-z0-9]/g,"").slice(0,3); if(prefix.length!==3) throw new Error("Project ID needs a three-character prefix."); const used=new Set(bases.map(item=>item.workspaceId)); const token=tokens.find(value=>/^[a-z2-7]{12}$/.test(value)&&!used.has(`${prefix}-${value}`)); if(!token) throw new Error("Unable to allocate a unique workspace ID."); const workspaceId=`${prefix}-${token}`;
 const prdFiles=request.prdFiles.map(file=>({...file})); const workspace={workspaceId,projectId:request.projectId,workspaceName:request.workspaceName.trim(),baseWorkspaceId:base.workspaceId,baseHeadRevisionId:base.headRevisionId,status:"extracting" as const,available:false as const,unavailableReason:"Extraction is still in progress; this workspace cannot be opened yet.",prdFiles}; return {workspace,extractionRequest:{workspaceId,projectId:request.projectId,baseWorkspaceId:base.workspaceId,baseHeadRevisionId:base.headRevisionId,prdFiles}};
}
export function markFixtureWorkspaceReadyForReview(workspace:CreatedWorkspaceFixture):ReadyForReviewWorkspaceFixture { const {unavailableReason:_,...ready}=workspace; return {...ready,status:"ready-for-review",available:true}; }
const stressProject=(base:ProjectFixture,id:string,name:string,summary:string):ProjectFixture=>({...base,id,name,lastActivity:summary,repository:{...base.repository,summary}});
const groupedStressText=(length:number,characterAt:(index:number)=>string)=>{
 let value="",groupSize=1,characterIndex=0;
 while(value.length<length){
  const separator=value?" ":"";
  const group=Array.from({length:groupSize},()=>characterAt(characterIndex++)).join("");
  value=(value+separator+group).slice(0,length);
  groupSize+=1;
 }
 return value;
};
// Test-only card inputs. IDs remain valid lowercase kebab-case; visible names and descriptions cover lowercase, uppercase, and mixed case at their input limits with progressive word groups for realistic wrapping.
export const projectCardStressFixtures=[
 stressProject(project,"lowercase-".repeat(4)+"fixturex",groupedStressText(projectCardStressLimits.name,()=>"a"),groupedStressText(projectCardStressLimits.description,()=>"a")),
 stressProject(processingProject,"uppercase-".repeat(4)+"fixturex",groupedStressText(projectCardStressLimits.name,()=>"A"),groupedStressText(projectCardStressLimits.description,()=>"A")),
 stressProject(reviewProject,"mixedcase-".repeat(4)+"fixturex",groupedStressText(projectCardStressLimits.name,index=>index%2?"b":"A"),groupedStressText(projectCardStressLimits.description,index=>index%2?"b":"A")),
] as const satisfies readonly ProjectFixture[];
const processingJobs={uploading:{id:"job-member-portal",projectId:"member-portal",workspaceId:"member-portal-upload",stage:"uploading",message:"Uploading documents",progress:18},extracting:{id:"job-member-portal",projectId:"member-portal",workspaceId:"member-portal-draft",stage:"extracting",message:"Extracting text and structure",progress:42},modeling:{id:"job-member-portal",projectId:"member-portal",workspaceId:"member-portal-draft",stage:"modeling",message:"Building the accumulated project model",progress:76},ready:{id:"job-member-portal",projectId:"member-portal",workspaceId:"member-portal-draft",stage:"ready",message:"Ready to review",progress:100},"needs-attention":{id:"job-supplier-access",projectId:"supplier-access",workspaceId:"supplier-access-draft",stage:"needs-attention",message:"Needs attention: re-upload the protected PDF",progress:68},failed:{id:"job-supplier-access",projectId:"supplier-access",workspaceId:"supplier-access-draft",stage:"failed",message:"Processing failed: try the upload again",progress:68}} satisfies Record<ProcessingStage,ProcessingJobFixture>;
export const fixtureScenarios:Record<FixtureScenario["id"],FixtureScenario>={"empty-library":{id:"empty-library",label:"Empty library",session:owner,projects:[],lens:{selectedPrdIds:[],mode:"highlight"}},"owner-ready":{id:"owner-ready",label:"Owner reviewing Atlas understanding",session:owner,projects:[project,processingProject,reviewProject],workspace,lens:{selectedPrdIds:[],mode:"highlight"}},"editor-ready":{id:"editor-ready",label:"Editor on a shared project",session:{name:"Raka Pratama",email:"raka@example.com",role:"editor"},projects:[{...project,isShared:true}],workspace,lens:{selectedPrdIds:["safara-increment-02"],mode:"highlight"}},"viewer-ready":{id:"viewer-ready",label:"Viewer inspecting a shared project",session:{name:"Sari Utami",email:"sari@example.com",role:"viewer"},projects:[{...project,isShared:true}],workspace,lens:{selectedPrdIds:["safara-increment-01"],mode:"isolate"}},"processing-uploading":{id:"processing-uploading",label:"Uploading documents",session:owner,projects:[project,processingProject],processingJob:processingJobs.uploading,lens:{selectedPrdIds:[],mode:"highlight"}},"processing-extracting":{id:"processing-extracting",label:"Extracting text and structure",session:owner,projects:[project,processingProject],processingJob:processingJobs.extracting,lens:{selectedPrdIds:[],mode:"highlight"}},"processing-modeling":{id:"processing-modeling",label:"Building the accumulated project model",session:owner,projects:[project,processingProject],processingJob:processingJobs.modeling,lens:{selectedPrdIds:[],mode:"highlight"}},"processing-ready":{id:"processing-ready",label:"Ready to review",session:owner,projects:[project,processingProject],processingJob:processingJobs.ready,lens:{selectedPrdIds:[],mode:"highlight"}},"processing-needs-attention":{id:"processing-needs-attention",label:"Processing needs attention",session:owner,projects:[attentionProject],processingJob:processingJobs["needs-attention"],lens:{selectedPrdIds:[],mode:"highlight"}},"processing-failed":{id:"processing-failed",label:"Processing failed",session:owner,projects:[attentionProject],processingJob:processingJobs.failed,lens:{selectedPrdIds:[],mode:"highlight"}},"approved-result":{id:"approved-result",label:"Approved Atlas and CES result",session:owner,projects:[project],workspace:{...workspace,atlasApproval:"approved",cesApproval:"approved",cesItems:workspace.cesItems.map(item=>({...item,coverage:"covered"}))},lens:{selectedPrdIds:[],mode:"highlight"}}};

export function resolveFixtureProjectRoute(scenario: FixtureScenario, projectId?: string, records: readonly FixtureRouteProjectRecord[] = []) {
  const fixtureRecord = projectId ? routeRecordFor(projectId, records) : undefined;
  const project = fixtureRecord?.project ?? (projectId ? scenario.projects.find((item) => item.id === projectId) : undefined);
  const workspace = fixtureRecord && scenario.workspace ? { ...scenario.workspace, project: fixtureRecord.project } : project && scenario.workspace?.project.id === project.id ? scenario.workspace : undefined;
  return { project, fixtureRecord, workspace, canOpenWorkspace: project?.status === "ready" && Boolean(workspace) };
}
export function resolveFixtureWorkspaceContent(scenario: FixtureScenario, route: ReturnType<typeof resolveFixtureProjectRoute>, workspaceId?: string) {
  if (!route.workspace || !route.fixtureRecord) return route.workspace;
  if (workspaceId === route.fixtureRecord.masterWorkspace.workspaceId) return { ...route.workspace, project: route.fixtureRecord.project, prds: [], workflowGroups: [], workflows: [], facts: [], changes: [], sourceAccounting: [], cesItems: [] };
  return { ...route.workspace, project: route.fixtureRecord.project };
}
export function getFixtureScenario(id:FixtureScenario["id"]="owner-ready"){return fixtureScenarios[id]} export const atlasWorkspaceFixture=getFixtureScenario("owner-ready");
