export type AccessRole = "owner" | "editor" | "viewer";
export type ProjectStatus = "ready" | "processing" | "needs-attention";
export type ProcessingStage = "uploading" | "extracting" | "modeling" | "ready" | "needs-attention" | "failed";
export type ApprovalState = "awaiting-approval" | "approved";
export type CesCoverageState = "covered" | "needs-review" | "out-of-scope" | "unresolved";
export type ChangeKind = "established" | "clarified" | "expanded" | "superseded" | "unresolved";

export type SourceEvidence = { id: string; understood: string; quote: string; documentId: string; documentName: string; page: number };
export type PrdFixture = { id: string; name: string; increment: string; publishedAt: string; pageCount: number; selectedByDefault?: boolean };
export type ProjectFixture = { id: string; name: string; status: ProjectStatus; prdCount: number; collaborators: number; lastActivity: string; isShared: boolean };
export type MembershipFixture = { id: string; name: string; email: string; role: AccessRole; status: "active" | "invited" | "removed" };
export type WorkflowNodeFixture = { id: string; title: string; note: string; kind: "activity" | "decision" | "outcome" | "warning"; prdIds: string[]; evidence: SourceEvidence };
export type WorkflowFixture = { id: string; groupId: string; title: string; summary: string; businessQuestion: string; roles: string[]; expectedResult: string; prdIds: string[]; nodes: WorkflowNodeFixture[]; evidence: SourceEvidence[] };
export type WorkflowGroupFixture = { id: string; order: string; title: string; summary: string; expectedResult: string; workflowIds: string[]; prdIds: string[]; support?: boolean };
export type FactFixture = { id: string; group: "Scope" | "People and responsibilities" | "Constraints" | "Information protection" | "Outputs" | "Commitments"; statement: string; evidence: SourceEvidence[] };
export type ChangeFixture = { id: string; kind: ChangeKind; summary: string; prdId: string; affectedIds: string[]; evidence: SourceEvidence[] };
export type CesItemFixture = { id: string; policy: string; obligation: string; linkedFactIds: string[]; concern: string; capabilityNeed: string; coverage: CesCoverageState; decision?: string; evidence: SourceEvidence[] };
export type ProcessingJobFixture = { id: string; projectId: string; stage: ProcessingStage; message: string; progress: number };

export type ProjectWorkspaceFixture = { project: ProjectFixture; prds: PrdFixture[]; memberships: MembershipFixture[]; workflowGroups: WorkflowGroupFixture[]; workflows: WorkflowFixture[]; facts: FactFixture[]; changes: ChangeFixture[]; cesItems: CesItemFixture[]; atlasApproval: ApprovalState; cesApproval: ApprovalState };
export type FixtureScenario = { id: "empty-library" | "owner-ready" | "editor-ready" | "viewer-ready" | "processing-uploading" | "processing-extracting" | "processing-modeling" | "processing-ready" | "processing-needs-attention" | "processing-failed" | "approved-result"; label: string; session: { name: string; email: string; role: AccessRole }; projects: ProjectFixture[]; workspace?: ProjectWorkspaceFixture; processingJob?: ProcessingJobFixture; lens: { selectedPrdIds: string[]; mode: "highlight" | "isolate" } };

const evidence: SourceEvidence = { id: "evidence-booking-review", understood: "A booking change is checked before it is confirmed.", quote: "Operations reviews the requested change before confirming the revised booking.", documentId: "safara-increment-01", documentName: "Safara Buyer Business PRD — Initial release", page: 12 };
const source = (id: string, understood: string, quote: string, documentId = "safara-increment-01", page = 1): SourceEvidence => ({ id, understood, quote, documentId, documentName: documentId === "safara-increment-02" ? "Safara Buyer Business PRD — Finance clarification" : documentId === "safara-increment-03" ? "Safara Buyer Business PRD — Operations expansion" : "Safara Buyer Business PRD — Initial release", page });
const node = (id: string, title: string, note: string, kind: WorkflowNodeFixture["kind"], prdIds: string[], understood: string, quote: string, documentId = prdIds[0], page = 1): WorkflowNodeFixture => ({ id, title, note, kind, prdIds, evidence: source(`${id}-evidence`, understood, quote, documentId, page) });
const project: ProjectFixture = { id: "safara", name: "Safara operations platform", status: "ready", prdCount: 3, collaborators: 4, lastActivity: "Atlas understanding is ready to review", isShared: false };
const workspace: ProjectWorkspaceFixture = {
  project,
  prds: [
    { id: "safara-increment-01", name: "Initial release", increment: "PRD 1", publishedAt: "14 May 2026", pageCount: 28, selectedByDefault: true },
    { id: "safara-increment-02", name: "Finance clarification", increment: "PRD 2", publishedAt: "02 June 2026", pageCount: 9 },
    { id: "safara-increment-03", name: "Operations expansion", increment: "PRD 3", publishedAt: "19 June 2026", pageCount: 14 },
  ],
  memberships: [
    { id: "nadia", name: "Nadia Hartono", email: "nadia@example.com", role: "owner", status: "active" },
    { id: "raka", name: "Raka Pratama", email: "raka@example.com", role: "editor", status: "active" },
    { id: "sari", name: "Sari Utami", email: "sari@example.com", role: "viewer", status: "active" },
    { id: "maya", name: "Maya Santoso", email: "maya@example.com", role: "viewer", status: "invited" },
  ],
  workflowGroups: [
    { id: "prepare", order: "01", title: "Prepare departure", summary: "Set up the package, schedule, and capacity before registrations begin.", expectedResult: "A departure can receive registrations", workflowIds: ["package", "schedule"], prdIds: ["safara-increment-01", "safara-increment-02"] },
    { id: "register", order: "02", title: "Register pilgrim", summary: "Record the pilgrim, assign an available departure, and establish the agreed obligation.", expectedResult: "A pilgrim has a departure and invoice", workflowIds: ["registration", "invoice"], prdIds: ["safara-increment-01", "safara-increment-03"] },
    { id: "requirements", order: "03", title: "Complete requirements", summary: "Review accepted payment, documents, and travel information.", expectedResult: "Every requirement can be assessed", workflowIds: ["payment", "documents"], prdIds: ["safara-increment-01", "safara-increment-02"] },
    { id: "readiness", order: "04", title: "Confirm travel readiness", summary: "Evaluate all required conditions and expose any blockers.", expectedResult: "Readiness is explainable", workflowIds: ["readiness"], prdIds: ["safara-increment-01"] },
    { id: "manifest", order: "05", title: "Finalize departure", summary: "Confirm eligible pilgrims and create a stable manifest snapshot.", expectedResult: "A final manifest is stable", workflowIds: ["manifest"], prdIds: ["safara-increment-01"] },
    { id: "support", order: "S", title: "Operational oversight", summary: "Reporting and activity history explain the operation without becoming a lifecycle stage.", expectedResult: "Management can inspect progress and accountability", workflowIds: ["reporting", "history"], prdIds: ["safara-increment-01", "safara-increment-02"], support: true },
  ],
  workflows: [
    { id: "package", groupId: "prepare", title: "Manage Umrah packages", summary: "Define the commercial package used by departure schedules.", businessQuestion: "How is a package prepared for use?", roles: ["Owner / Admin"], expectedResult: "An active package is available for scheduling", prdIds: ["safara-increment-01", "safara-increment-02"], nodes: [node("package-create", "Create package", "Name, duration, price, and facilities", "activity", ["safara-increment-01"], "Atlas understands this as the durable commercial definition used for future schedules.", "Owner/Admin can create, view, update, and deactivate Umrah packages.", "safara-increment-01", 2), node("package-activate", "Activate package", "Only active packages enter operations", "outcome", ["safara-increment-02"], "Atlas understands the clarification as an ownership boundary for package maintenance.", "Only Owner/Admin may manage packages and departure schedules.", "safara-increment-02", 1)], evidence: [evidence] },
    { id: "schedule", groupId: "prepare", title: "Open a departure schedule", summary: "Attach dates, route, and capacity to a package.", businessQuestion: "How does a departure become available?", roles: ["Owner / Admin"], expectedResult: "A schedule is open for registration", prdIds: ["safara-increment-01"], nodes: [node("schedule-details", "Set schedule details", "Dates, route, and accommodation", "activity", ["safara-increment-01"], "Atlas understands the schedule as the operational instance of a package.", "Admin enters dates, route, airline, and hotel information for the departure.", "safara-increment-01", 4), node("schedule-capacity", "Set capacity", "Define available seats", "decision", ["safara-increment-01"], "Atlas understands capacity as a guard on registrations.", "The application shows registered pilgrims and remaining quota.", "safara-increment-01", 5)], evidence: [evidence] },
    { id: "registration", groupId: "register", title: "Register a pilgrim", summary: "Choose a departure, check capacity, and preserve the agreement.", businessQuestion: "How is a pilgrim registered today?", roles: ["Owner / Admin"], expectedResult: "Registration succeeds or enters a waiting path", prdIds: ["safara-increment-01", "safara-increment-03"], nodes: [node("registration-select", "Choose departure", "The selected schedule must be open", "activity", ["safara-increment-01"], "Atlas understands the departure as the source of timing and capacity.", "Pilgrims are registered to the selected departure schedule.", "safara-increment-01", 7), node("registration-capacity", "Seat available?", "Check schedule status and remaining quota", "decision", ["safara-increment-01", "safara-increment-03"], "Atlas understands the newer PRD as expanding the full-capacity branch, not replacing the capacity check.", "If quota is full, a prospective pilgrim can be added to the waiting list.", "safara-increment-03", 1), node("registration-waiting", "Offer released seat", "Contact the first eligible waiting pilgrim", "outcome", ["safara-increment-03"], "Atlas understands the increment as a queue-based outcome after capacity returns.", "When a seat becomes available, the first waiting candidate is offered the seat.", "safara-increment-03", 2)], evidence: [evidence] },
    { id: "invoice", groupId: "register", title: "Create pilgrim invoice", summary: "Preserve the agreed amount independently of later package edits.", businessQuestion: "How is the payable amount established?", roles: ["System", "Finance"], expectedResult: "The pilgrim has a stable remaining balance", prdIds: ["safara-increment-01"], nodes: [node("invoice-agreement", "Read agreed price", "Use the price captured at registration", "activity", ["safara-increment-01"], "Atlas understands that later package changes cannot rewrite a completed agreement.", "Package price changes do not change the price already agreed at registration.", "safara-increment-01", 8), node("invoice-balance", "Calculate remaining balance", "Agreed price less accepted payments", "outcome", ["safara-increment-01"], "Atlas understands the balance as a derived operational value.", "Remaining payment is calculated from the agreed price minus accepted payments.", "safara-increment-01", 9)], evidence: [evidence] },
    { id: "payment", groupId: "requirements", title: "Review pilgrim payments", summary: "Record payment evidence and control when balance decreases.", businessQuestion: "How does a payment affect the invoice?", roles: ["Finance"], expectedResult: "Only accepted payments reduce the remaining balance", prdIds: ["safara-increment-01", "safara-increment-02"], nodes: [node("payment-record", "Record payment", "Capture amount, date, method, and reference", "activity", ["safara-increment-01"], "Atlas understands this as recording a payment claim before it affects the obligation.", "Finance can record pilgrim payments together with their references.", "safara-increment-01", 10), node("payment-review", "Accept or reject evidence", "Finance owns the review", "decision", ["safara-increment-02"], "Atlas understands the later PRD as assigning review responsibility to Finance.", "Finance reviews payment evidence and may accept or reject it.", "safara-increment-02", 2), node("payment-balance", "Update remaining balance", "Only accepted value reduces the balance", "outcome", ["safara-increment-01"], "Atlas understands accepted value as the only financial state transition.", "Accepted payment reduces the remaining payment; pending and rejected payment do not.", "safara-increment-01", 11)], evidence: [evidence] },
    { id: "documents", groupId: "requirements", title: "Review pilgrim documents", summary: "Upload, review, validate, or reject required documents.", businessQuestion: "How does a document become valid?", roles: ["Operations"], expectedResult: "Each required document has an explainable status", prdIds: ["safara-increment-01", "safara-increment-02"], nodes: [node("documents-upload", "Upload document", "Attach the required pilgrim file", "activity", ["safara-increment-01"], "Atlas understands this as the entry into a controlled review lifecycle.", "Pilgrim documents can be uploaded for review.", "safara-increment-01", 13), node("documents-review", "Review completeness", "Operations checks validity", "decision", ["safara-increment-02"], "Atlas understands the clarification as assigning the responsibility to Operations.", "Operations reviews pilgrim documents and updates travel status.", "safara-increment-02", 3), node("documents-outcome", "Mark valid or rejected", "A rejection includes a reason", "outcome", ["safara-increment-01"], "Atlas understands that rejection remains actionable only if the reason is visible.", "Rejected documents must include a reason.", "safara-increment-01", 14)], evidence: [evidence] },
    { id: "readiness", groupId: "readiness", title: "Decide travel readiness", summary: "Evaluate every required condition and expose all blockers.", businessQuestion: "When is a pilgrim Ready or Blocked?", roles: ["System", "Operations"], expectedResult: "The readiness result is complete and explainable", prdIds: ["safara-increment-01"], nodes: [node("readiness-inputs", "Read current conditions", "Balance, documents, and travel status", "activity", ["safara-increment-01"], "Atlas understands readiness as a view over current accepted operational state.", "Readiness is calculated from payment, document, and travel conditions.", "safara-increment-01", 16), node("readiness-all", "All conditions met?", "Evaluate every required condition", "decision", ["safara-increment-01"], "Atlas understands this as an AND decision rather than a score.", "A pilgrim is Ready only when every requirement is fulfilled.", "safara-increment-01", 17), node("readiness-result", "Mark Ready or Blocked", "Show every blocking reason", "warning", ["safara-increment-01"], "Atlas understands a missing condition as a visible blocker, not a hidden failure.", "If one requirement is not met, the pilgrim status becomes Blocked.", "safara-increment-01", 17)], evidence: [evidence] },
    { id: "manifest", groupId: "manifest", title: "Finalize departure manifest", summary: "Include Ready pilgrims and create a stable snapshot.", businessQuestion: "How does a manifest become final?", roles: ["Operations"], expectedResult: "The final departure list remains historically stable", prdIds: ["safara-increment-01"], nodes: [node("manifest-candidates", "View candidates", "Start from the selected departure", "activity", ["safara-increment-01"], "Atlas understands the manifest as a departure-specific selection.", "Operations can view manifest candidates for a departure.", "safara-increment-01", 19), node("manifest-ready", "Ready only?", "Blocked pilgrims cannot continue", "decision", ["safara-increment-01"], "Atlas understands readiness as the eligibility guard for finalization.", "Only pilgrims with Ready status can be included in the final manifest.", "safara-increment-01", 20), node("manifest-final", "Finalize and export", "Create a PDF or Excel snapshot", "outcome", ["safara-increment-01"], "Atlas understands finalization as making the historical list stable.", "After finalization, manifest contents do not change automatically when pilgrim data changes.", "safara-increment-01", 21)], evidence: [evidence] },
    { id: "reporting", groupId: "support", title: "Review dashboards and reports", summary: "Summarize operational progress without becoming a lifecycle step.", businessQuestion: "How does management inspect the operation?", roles: ["Owner / Admin"], expectedResult: "Management sees current operational totals", prdIds: ["safara-increment-01"], nodes: [node("reporting-read", "Read operational data", "Use the accepted project state", "activity", ["safara-increment-01"], "Atlas understands reports as projections of operational data, not a separate operational truth.", "Dashboards and reports use the application's operational data.", "safara-increment-01", 24), node("reporting-export", "Export report", "Produce Excel output", "outcome", ["safara-increment-01"], "Atlas understands the report as a handover output.", "Reports can be downloaded in Excel format.", "safara-increment-01", 25)], evidence: [evidence] },
    { id: "history", groupId: "support", title: "Inspect activity history", summary: "Preserve who changed important operational information.", businessQuestion: "How are material changes accountable?", roles: ["Owner / Admin"], expectedResult: "Important changes remain traceable", prdIds: ["safara-increment-01", "safara-increment-02"], nodes: [node("history-record", "Record activity", "User, time, action, and affected data", "activity", ["safara-increment-01"], "Atlas understands activity history as an accountability record.", "Activity history records who performed an action and when.", "safara-increment-01", 26), node("history-review", "Review history", "Owner/Admin inspects accountability", "outcome", ["safara-increment-02"], "Atlas understands this clarification as defining oversight access.", "Owner/Admin can inspect activity history.", "safara-increment-02", 4)], evidence: [evidence] },
  ],
  facts: [{ id: "fact-review", group: "People and responsibilities", statement: "Operations reviews requested booking changes.", evidence: [evidence] }],
  changes: [{ id: "change-finance", kind: "clarified", summary: "Finance review is required for payment-impacting changes.", prdId: "safara-increment-02", affectedIds: ["package", "payment", "fact-review"], evidence: [evidence] }],
  cesItems: [{ id: "ces-access", policy: "Access accountability", obligation: "Account for who may review and confirm a change.", linkedFactIds: ["fact-review"], concern: "An unaccounted reviewer could approve a sensitive change.", capabilityNeed: "The solution must make review responsibility visible.", coverage: "needs-review", decision: "Confirm the accountability record for Finance review.", evidence: [evidence] }],
  atlasApproval: "awaiting-approval", cesApproval: "awaiting-approval",
};

const processingProject: ProjectFixture = { id: "member-portal", name: "Member portal refresh", status: "processing", prdCount: 2, collaborators: 2, lastActivity: "Extracting project facts", isShared: true };
const attentionProject: ProjectFixture = { id: "supplier-access", name: "Supplier access update", status: "needs-attention", prdCount: 1, collaborators: 1, lastActivity: "One PDF needs another upload", isShared: false };
const owner = { name: "Nadia Hartono", email: "nadia@example.com", role: "owner" } as const;
const processingJobs = {
  uploading: { id: "job-member-portal", projectId: "member-portal", stage: "uploading", message: "Uploading documents", progress: 18 },
  extracting: { id: "job-member-portal", projectId: "member-portal", stage: "extracting", message: "Extracting text and structure", progress: 42 },
  modeling: { id: "job-member-portal", projectId: "member-portal", stage: "modeling", message: "Building the accumulated project model", progress: 76 },
  ready: { id: "job-member-portal", projectId: "member-portal", stage: "ready", message: "Ready to review", progress: 100 },
  "needs-attention": { id: "job-supplier-access", projectId: "supplier-access", stage: "needs-attention", message: "Needs attention: re-upload the protected PDF", progress: 68 },
  failed: { id: "job-supplier-access", projectId: "supplier-access", stage: "failed", message: "Processing failed: try the upload again", progress: 68 },
} satisfies Record<ProcessingStage, ProcessingJobFixture>;

export const fixtureScenarios: Record<FixtureScenario["id"], FixtureScenario> = {
  "empty-library": { id: "empty-library", label: "Empty library", session: owner, projects: [], lens: { selectedPrdIds: [], mode: "highlight" } },
  "owner-ready": { id: "owner-ready", label: "Owner reviewing Atlas understanding", session: owner, projects: [project, processingProject], workspace, lens: { selectedPrdIds: [], mode: "highlight" } },
  "editor-ready": { id: "editor-ready", label: "Editor on a shared project", session: { name: "Raka Pratama", email: "raka@example.com", role: "editor" }, projects: [{ ...project, isShared: true }], workspace, lens: { selectedPrdIds: ["safara-increment-02"], mode: "highlight" } },
  "viewer-ready": { id: "viewer-ready", label: "Viewer inspecting a shared project", session: { name: "Sari Utami", email: "sari@example.com", role: "viewer" }, projects: [{ ...project, isShared: true }], workspace, lens: { selectedPrdIds: ["safara-increment-01"], mode: "isolate" } },
  "processing-uploading": { id: "processing-uploading", label: "Uploading documents", session: owner, projects: [project, processingProject], processingJob: processingJobs.uploading, lens: { selectedPrdIds: [], mode: "highlight" } },
  "processing-extracting": { id: "processing-extracting", label: "Extracting text and structure", session: owner, projects: [project, processingProject], processingJob: processingJobs.extracting, lens: { selectedPrdIds: [], mode: "highlight" } },
  "processing-modeling": { id: "processing-modeling", label: "Building the accumulated project model", session: owner, projects: [project, processingProject], processingJob: processingJobs.modeling, lens: { selectedPrdIds: [], mode: "highlight" } },
  "processing-ready": { id: "processing-ready", label: "Ready to review", session: owner, projects: [project, processingProject], processingJob: processingJobs.ready, lens: { selectedPrdIds: [], mode: "highlight" } },
  "processing-needs-attention": { id: "processing-needs-attention", label: "Processing needs attention", session: owner, projects: [attentionProject], processingJob: processingJobs["needs-attention"], lens: { selectedPrdIds: [], mode: "highlight" } },
  "processing-failed": { id: "processing-failed", label: "Processing failed", session: owner, projects: [attentionProject], processingJob: processingJobs.failed, lens: { selectedPrdIds: [], mode: "highlight" } },
  "approved-result": { id: "approved-result", label: "Approved Atlas and CES result", session: owner, projects: [project], workspace: { ...workspace, atlasApproval: "approved", cesApproval: "approved", cesItems: workspace.cesItems.map((item) => ({ ...item, coverage: "covered" })) }, lens: { selectedPrdIds: [], mode: "highlight" } },
};

export function getFixtureScenario(id: FixtureScenario["id"] = "owner-ready") {
  return fixtureScenarios[id];
}

// Compatibility export for the initial demo while screens move to named scenarios.
export const atlasWorkspaceFixture = getFixtureScenario("owner-ready");
