"use client";
import Link from "next/link";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { ProfileMenu } from "./ProfileMenu";
import { TopBar } from "./TopBar";
import type { ProjectFixture, ProjectWorkspaceFixture } from "@atlas/fixtures";
type User={name:string;email:string;role:"owner"|"editor"|"viewer"}; type Destination="projects"|"workflow"|"facts"|"ces"|"changes";
type Props={user:User;children:ReactNode;projects:ProjectFixture[];selectedProjectId?:string;workspace?:ProjectWorkspaceFixture;active?:Destination;projectNavigation?:boolean;sidebarAction?:ReactNode;topbarAction?:ReactNode};
const navigation:[Destination,string][]=[["workflow","Main Workflow"],["facts","Project Facts"],["ces","CES Result"],["changes","Changes Done"]];
export function AppShell({user,children,projects,selectedProjectId,workspace,active="projects",projectNavigation=false,sidebarAction,topbarAction}:Props){const[menu,setMenu]=useState(false),[collapsed,setCollapsed]=useState(false);const ref=useRef<HTMLDivElement>(null);const current=projects.find((project)=>project.id===selectedProjectId);const workflowCount=current && workspace && current.id===workspace.project.id?workspace.workflows.length:undefined;useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setMenu(false)};document.addEventListener("keydown",close);return()=>document.removeEventListener("keydown",close)},[]);useEffect(()=>{if(!menu)return;const close=(e:PointerEvent)=>{if(!ref.current?.contains(e.target as Node))setMenu(false)};document.addEventListener("pointerdown",close);return()=>document.removeEventListener("pointerdown",close)},[menu]);return <div className={`app-shell ${collapsed?"sidebar-collapsed":""}`}><TopBar className="app-header" variant="workspace"><Link className="brand" href="/demo"><span>A</span>Atlas</Link><div className="topbar-actions">{topbarAction}<button className="mobile-menu" onClick={()=>setCollapsed(!collapsed)} type="button">Menu</button></div></TopBar><aside className="navigation" id="app-navigation"><button aria-label={collapsed?"Expand sidebar":"Collapse sidebar"} className="sidebar-toggle" onClick={()=>setCollapsed(!collapsed)} type="button">‹</button><ProfileMenu user={user}/><div className="project-switcher" ref={ref}><button aria-expanded={menu} onClick={()=>setMenu(!menu)} type="button"><span>{current?current.name[0]:"⌁"}</span><div><small>{current?"Current project":"Project"}</small><strong>{current?current.name:"Select a project"}</strong><em>{current?`${current.prdCount} PRDs${workflowCount===undefined?"":` · ${workflowCount} workflow pages`}`:`${projects.length} available projects`}</em></div><i>⌄</i></button>{menu&&<div className="project-switcher-menu"><header><strong>All projects</strong><small>{projects.length} projects</small></header>{projects.map(project=>{const isCurrent=current?.id===project.id;const detail=<><span>{project.name[0]}</span><div><strong>{project.name}</strong><small>{project.prdCount} PRDs · {project.status==="ready"?"ready to review":project.status}</small></div>{isCurrent&&<em>Current</em>}</>;return project.status==="ready"?<Link className={isCurrent?"is-current":""} href={`/demo?projectId=${project.id}&view=workflow`} key={project.id} onClick={()=>setMenu(false)}>{detail}</Link>:<span className="is-unavailable" key={project.id}>{detail}</span>})}<p>Select a ready project to inspect its workflow.</p></div>}</div><div className="sidebar-action">{sidebarAction}</div>{projectNavigation&&<nav aria-label="Project navigation">{navigation.map(([id,label])=><Link aria-current={active===id?"page":undefined} className={active===id?"nav-active":""} href="/demo" key={id}>{label}</Link>)}</nav>}</aside><main className="app-content">{children}</main></div>}
