"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import type { ProjectFixture, ProjectWorkspaceFixture } from "@atlas/fixtures";
import { AppShell } from "./AppShell";
import { Dialog } from "./Dialog";
import { OperationalModel } from "./OperationalModel";
import { KnowledgeFactsLayout } from "./KnowledgeFactsLayout";
import { PrdLensControl } from "./PrdLensControl";
import { demoHref, useWorkspaceApprovals, useWorkspaceLens, type WorkspaceLens } from "./WorkspaceLens";

type User = { name: string; email: string; role: "owner" | "editor" | "viewer" };
type View = "facts" | "changes";
const matches = (ids: string[], selected: string[]) => !selected.length || ids.some((id) => selected.includes(id));

export function ProjectKnowledge({ user, projects, workspace, view, initialLens, scenario, initialFactId }: { user: User; projects: ProjectFixture[]; workspace: ProjectWorkspaceFixture; view: View; initialLens: WorkspaceLens; scenario?: string; initialFactId?: string }) {
  const { lens, set, toggle } = useWorkspaceLens(initialLens);
  const [accountingPrd, setAccountingPrd] = useState<string | null>(null);
  const { approvals, approve } = useWorkspaceApprovals(workspace.project.id, { atlas: workspace.atlasApproval, ces: workspace.cesApproval });
  const active = lens.selectedPrdIds.length > 0;
  const isolate = active && lens.mode === "isolate";
  const facts = useMemo(() => workspace.facts.filter((fact) => !isolate || matches(fact.prdIds, lens.selectedPrdIds)), [isolate, lens.selectedPrdIds, workspace.facts]);
  const changes = useMemo(() => workspace.changes.filter((change) => !isolate || lens.selectedPrdIds.includes(change.prdId)), [isolate, lens.selectedPrdIds, workspace.changes]);
  const byPrd = workspace.prds.map((prd) => ({ prd, changes: changes.filter((change) => change.prdId === prd.id) })).filter((group) => group.changes.length);
  return <AppShell active={view} projectNavigation projects={projects} routeContext={{ scenario, prd: lens.selectedPrdIds.length ? lens.selectedPrdIds.join(",") : undefined, lens: isolate ? "isolate" : undefined }} selectedProjectId={workspace.project.id} topbarAction={<PrdLensControl lens={lens} prds={workspace.prds} set={set} toggle={toggle} onAccounting={setAccountingPrd} />} user={user} workspace={workspace}>
    <section className="knowledge-page">
      {view === "facts" ? <FactsView active={active} approval={approvals.atlas} facts={facts} initialFactId={initialFactId} isolate={isolate} lens={lens} onApprove={() => approve("atlas")} workspace={workspace} user={user} /> : <><header className="workspace-page-heading knowledge-heading changes-heading"><div><p className="workflow-kicker">Accumulated change record</p><h1>Changes Done</h1><p>History grouped by PRD increment. Every change remains traceable to its source wording and the project knowledge it affected.</p></div></header><section className="change-stack" aria-label="Changes grouped by PRD increment">{byPrd.map(({ prd, changes: items }) => <section className={active && !lens.selectedPrdIds.includes(prd.id) ? "is-muted" : ""} key={prd.id}><header className="increment-meta"><b>{prd.increment}</b><h2>{prd.name}</h2><p>{prd.publishedAt} · {prd.pageCount} pages</p></header><div className="change-list">{items.map((change) => <article className={change.kind === "unresolved" ? "is-question" : ""} key={change.id}><em>{change.kind}</em><div className="change-copy"><h2>{change.title}</h2><p>{change.summary}</p><details><summary>Read source evidence</summary><p>{change.evidence[0].understood}</p><blockquote>“{change.evidence[0].quote}”</blockquote><small>{change.evidence[0].documentName} · page {change.evidence[0].page}</small></details></div><DestinationLink destination={change.destination} lens={lens} projectId={workspace.project.id} /></article>)}</div></section>)}</section>{!changes.length && <Empty />}</>}
    </section>{accountingPrd && <Accounting lens={lens} prdId={accountingPrd} projectId={workspace.project.id} workspace={workspace} onClose={() => setAccountingPrd(null)} onSelectOnly={(id) => { set({ selectedPrdIds: [id], mode: "highlight" }); setAccountingPrd(null); }} />}
  </AppShell>;
}

function FactsView({ active, approval, facts, initialFactId, isolate, lens, onApprove, user, workspace }: { active: boolean; approval: "awaiting-approval" | "approved"; facts: ProjectWorkspaceFixture["facts"]; initialFactId?: string; isolate: boolean; lens: WorkspaceLens; onApprove: () => void; user: User; workspace: ProjectWorkspaceFixture }) {
  return <KnowledgeFactsLayout active={active} approval={{ status: approval, pendingText: "Review workflows, facts, changes, and evidence before confirming the accumulated understanding.", approvedText: "The accumulated workflow, facts, changes, and evidence have been approved.", reviewLabel: "Review evidence", approveLabel: "Approve understanding", onApprove, onReview: () => facts[0] && document.getElementById(facts[0].id)?.scrollIntoView({ behavior: "smooth", block: "start" }) }} facts={facts} heading={{ kicker: "Current non-workflow knowledge", title: "Project Facts", description: "Durable knowledge grouped by meaning, not document order. Each source-grounded fact stays connected to the detailed workflows it informs." }} initialFactId={initialFactId} isolate={isolate} lens={lens} operationalModel={<OperationalModel className="mobile-context-primary" middleMetric={{ label: "Project facts", value: workspace.facts.reduce((total, fact) => total + fact.rows.length, 0) }} workspace={workspace} />} user={user} workspace={workspace} />;
}

function destinationHref(projectId: string, lens: WorkspaceLens, destination: ProjectWorkspaceFixture["changes"][number]["destination"]) { const view = destination.type === "workflow" ? "workflow" : destination.type === "fact" ? "facts" : destination.type === "ces" ? "ces" : "changes"; const target = destination.type === "workflow" ? { workflowId: destination.targetId } : destination.type === "fact" ? { factId: destination.targetId } : destination.type === "ces" ? { cesItemId: destination.targetId } : {}; return demoHref({ projectId, view, prd: lens.selectedPrdIds.length ? lens.selectedPrdIds.join(",") : undefined, lens: lens.mode === "isolate" ? "isolate" : undefined, ...target }); }
function DestinationLink({ destination, lens, projectId }: { destination: ProjectWorkspaceFixture["changes"][number]["destination"]; lens: WorkspaceLens; projectId: string }) { if (destination.type === "unresolved" || destination.type === "project") return <span className="change-destination">{destination.label}</span>; return <Link href={destinationHref(projectId, lens, destination)}>Open destination →<small>{destination.label}</small></Link>; }
function Accounting({ prdId, projectId, lens, workspace, onClose, onSelectOnly }: { prdId: string; projectId: string; lens: WorkspaceLens; workspace: ProjectWorkspaceFixture; onClose: () => void; onSelectOnly: (id: string) => void }) { const prd = workspace.prds.find((item) => item.id === prdId)!; const statements = workspace.sourceAccounting.filter((item) => item.prdId === prdId); const placed = statements.filter((item) => item.destination.type !== "unresolved").length; return <Dialog onClose={onClose} title={`Source document accounting — ${prd.name}`}><section className="source-accounting-modal"><p>{prd.increment} · {prd.publishedAt}</p><div className="accounting-summary"><span><b>{statements.length}</b> statements found</span><span><b>{placed}</b> placed in project</span><span><b>{statements.length - placed}</b> needs an answer</span></div>{statements.map((statement) => <article className={statement.destination.type === "unresolved" ? "is-question" : ""} key={statement.id}><span>{statement.destination.type === "unresolved" ? "?" : "✓"}</span><div><small>Source statement</small><blockquote>“{statement.statement}”</blockquote><b>{statement.destination.label}</b></div><DestinationLink destination={statement.destination} lens={lens} projectId={projectId} /></article>)}<footer><p>Every source statement resolves to Main Workflow, Project Facts, CES Result, Needs Answer, or an explicit exclusion.</p><button onClick={() => onSelectOnly(prdId)} type="button">Use this PRD as global lens</button></footer></section></Dialog>; }
function Empty() { return <section className="knowledge-empty"><strong>No selected contribution here</strong><p>Choose another PRD or turn off isolation to restore the accumulated project context.</p></section>; }
