"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import type { ProjectFixture, ProjectWorkspaceFixture } from "@atlas/fixtures";
import { AppShell } from "./AppShell";
import { Dialog } from "./Dialog";
import { OperationalModel } from "./OperationalModel";
import { useWorkspaceLens, type WorkspaceLens } from "./WorkspaceLens";

type User = { name: string; email: string; role: "owner" | "editor" | "viewer" };
type View = "facts" | "changes";
const matches = (ids: string[], selected: string[]) => !selected.length || ids.some((id) => selected.includes(id));

export function ProjectKnowledge({ user, projects, workspace, view, initialLens }: { user: User; projects: ProjectFixture[]; workspace: ProjectWorkspaceFixture; view: View; initialLens: WorkspaceLens }) {
  const { lens, set, toggle } = useWorkspaceLens(initialLens);
  const [accountingPrd, setAccountingPrd] = useState<string | null>(null);
  const [approval, setApproval] = useState(workspace.atlasApproval);
  const active = lens.selectedPrdIds.length > 0;
  const isolate = active && lens.mode === "isolate";
  const facts = useMemo(() => workspace.facts.filter((fact) => !isolate || matches(fact.prdIds, lens.selectedPrdIds)), [isolate, lens.selectedPrdIds, workspace.facts]);
  const changes = useMemo(() => workspace.changes.filter((change) => !isolate || lens.selectedPrdIds.includes(change.prdId)), [isolate, lens.selectedPrdIds, workspace.changes]);
  const byPrd = workspace.prds.map((prd) => ({ prd, changes: changes.filter((change) => change.prdId === prd.id) })).filter((group) => group.changes.length);
  return <AppShell active={view} projectNavigation projects={projects} routeContext={{ prd: lens.selectedPrdIds.length ? lens.selectedPrdIds.join(",") : undefined, lens: isolate ? "isolate" : undefined }} selectedProjectId={workspace.project.id} topbarAction={<LensControl workspace={workspace} lens={lens} set={set} toggle={toggle} onAccounting={setAccountingPrd} />} user={user} workspace={workspace}>
    <section className="knowledge-page">
      {view === "facts" ? <FactsView active={active} approval={approval} facts={facts} isolate={isolate} lens={lens} onApprove={() => setApproval("approved")} workspace={workspace} user={user} /> : <><header className="workspace-page-heading knowledge-heading changes-heading"><div><p className="workflow-kicker">Accumulated change record</p><h1>Changes Done</h1><p>History grouped by PRD increment. Every change remains traceable to its source wording and the project knowledge it affected.</p></div></header><section className="change-stack" aria-label="Changes grouped by PRD increment">{byPrd.map(({ prd, changes: items }) => <section className={active && !lens.selectedPrdIds.includes(prd.id) ? "is-muted" : ""} key={prd.id}><header className="increment-meta"><b>{prd.increment}</b><h2>{prd.name}</h2><p>{prd.publishedAt} · {prd.pageCount} pages</p></header><div className="change-list">{items.map((change) => <article className={change.kind === "unresolved" ? "is-question" : ""} key={change.id}><em>{change.kind}</em><div className="change-copy"><h2>{change.title}</h2><p>{change.summary}</p><details><summary>Read source evidence</summary><p>{change.evidence[0].understood}</p><blockquote>“{change.evidence[0].quote}”</blockquote><small>{change.evidence[0].documentName} · page {change.evidence[0].page}</small></details></div><DestinationLink destination={change.destination} lens={lens} projectId={workspace.project.id} /></article>)}</div></section>)}</section>{!changes.length && <Empty />}</>}
    </section>{accountingPrd && <Accounting lens={lens} prdId={accountingPrd} projectId={workspace.project.id} workspace={workspace} onClose={() => setAccountingPrd(null)} onSelectOnly={(id) => { set({ selectedPrdIds: [id], mode: "highlight" }); setAccountingPrd(null); }} />}
  </AppShell>;
}

function FactsView({ active, approval, facts, isolate, lens, onApprove, user, workspace }: { active: boolean; approval: "awaiting-approval" | "approved"; facts: ProjectWorkspaceFixture["facts"]; isolate: boolean; lens: WorkspaceLens; onApprove: () => void; user: User; workspace: ProjectWorkspaceFixture }) {
  const firstFactId = facts[0]?.id;
  return <>
    <section aria-label="Atlas understanding approval" className={`workflow-approval-bar ${approval === "approved" ? "is-approved" : ""}`}><div><strong>Atlas understanding · {approval === "approved" ? "Approved" : "Awaiting approval"}</strong><p>{approval === "approved" ? "The accumulated workflow, facts, changes, and evidence have been approved." : "Review workflows, facts, changes, and evidence before confirming the accumulated understanding."}</p></div><div><button onClick={() => firstFactId && document.getElementById(firstFactId)?.scrollIntoView({ behavior: "smooth", block: "start" })} type="button">Review evidence</button>{user.role === "owner" && approval === "awaiting-approval" && <button className="is-primary" onClick={onApprove} type="button">Approve understanding</button>}</div></section>
    <header className="workspace-page-heading"><div><p className="workflow-kicker">Current non-workflow knowledge</p><h1>Project Facts</h1><p>Durable knowledge grouped by meaning, not document order. Each source-grounded fact stays connected to the detailed workflows it informs.</p></div></header>
    <div className="facts-refactor-layout"><section className="knowledge-list" aria-label="Project fact groups">{facts.map((fact) => { const rows = isolate ? fact.rows.filter((row) => matches(row.prdIds, lens.selectedPrdIds)) : fact.rows; const matched = matches(fact.prdIds, lens.selectedPrdIds); return <details className={active && !matched ? "is-muted" : ""} id={fact.id} key={fact.id}><summary><span>{fact.number}</span><div><h2>{fact.title}</h2><p>{fact.summary}</p></div><small><b>{rows.length} fact{rows.length === 1 ? "" : "s"}</b>{fact.prdIds.map((id) => workspace.prds.find((prd) => prd.id === id)?.increment).filter(Boolean).join(" · ")}</small></summary><div className="knowledge-list-body">{rows.map((row) => <article className={active && matches(row.prdIds, lens.selectedPrdIds) ? "is-matched" : ""} key={row.id}><div><small>Original PRD wording</small><blockquote>“{row.statement}”</blockquote><p><strong>Atlas interpretation:</strong> {row.evidence[0].understood}</p><details><summary>Read source evidence</summary><blockquote>“{row.evidence[0].quote}”</blockquote><small>{row.evidence[0].documentName} · page {row.evidence[0].page}</small></details></div><aside><small>Related main workflow</small>{row.relatedWorkflowIds.slice(0, 1).map((workflowId) => { const workflow = workspace.workflows.find((item) => item.id === workflowId); const group = workspace.workflowGroups.find((item) => item.id === workflow?.groupId); return workflow && <Link href={`/demo?projectId=${workspace.project.id}&view=workflow`} key={workflowId}><strong>{group?.order} · {group?.title}</strong><span>{workflow.title} →</span></Link>; })}</aside></article>)}</div></details>; })}</section><aside className="facts-operational-rail"><OperationalModel middleMetric={{ label: "Project facts", value: workspace.facts.reduce((total, fact) => total + fact.rows.length, 0) }} workspace={workspace} /></aside></div>
    {!facts.length && <Empty />}
  </>;
}

function LensControl({ workspace, lens, set, toggle, onAccounting }: { workspace: ProjectWorkspaceFixture; lens: WorkspaceLens; set: (lens: WorkspaceLens) => void; toggle: (id: string) => void; onAccounting: (id: string) => void }) { const [open, setOpen] = useState(false); const active = lens.selectedPrdIds.length > 0; return <div className="topbar-prd-lens"><button aria-expanded={open} className="topbar-prd-trigger" onClick={() => setOpen(!open)} type="button"><span>⌁</span><div><small>PRD lens</small><strong>{active ? <>{lens.selectedPrdIds.length} PRD{lens.selectedPrdIds.length > 1 ? "s" : ""}<span className="lens-selected-suffix"> selected</span></> : "All PRDs"}</strong></div><i>⌄</i></button>{open && <div className="prd-lens-popover"><header><div><span className="workflow-kicker">Global project filter</span><strong>Choose one or more PRDs</strong></div><button aria-label="Close PRD lens" onClick={() => setOpen(false)} type="button">×</button></header><button className={!active ? "is-selected" : ""} onClick={() => set({ selectedPrdIds: [], mode: "highlight" })} type="button"><span>{!active ? "✓" : ""}</span><div><strong>All PRDs</strong><small>Complete accumulated project</small></div></button>{workspace.prds.map((prd) => <button className={lens.selectedPrdIds.includes(prd.id) ? "is-selected" : ""} key={prd.id} onClick={() => toggle(prd.id)} type="button"><span>{lens.selectedPrdIds.includes(prd.id) ? "✓" : ""}</span><div><strong>{prd.increment}</strong><small>{prd.name} · {prd.pageCount} pages</small></div></button>)}<label aria-label="Hide unselected PRD data" className={!active ? "is-disabled" : ""}><input checked={lens.mode === "isolate" && active} disabled={!active} onChange={(event) => set({ ...lens, mode: event.target.checked ? "isolate" : "highlight" })} type="checkbox" /><i /><div><strong>Hide unselected PRD data</strong><small>{lens.mode === "isolate" && active ? "Isolation mode" : "Contextual highlight mode"}</small></div></label><footer><button onClick={() => onAccounting(active ? lens.selectedPrdIds[0] : workspace.prds[0].id)} type="button">Source accounting</button><button onClick={() => setOpen(false)} type="button">Done</button></footer></div>}</div>; }
function destinationHref(projectId: string, lens: WorkspaceLens, destination: ProjectWorkspaceFixture["changes"][number]["destination"]) { const view = destination.type === "workflow" ? "workflow" : destination.type === "fact" ? "facts" : destination.type === "ces" ? "ces" : "changes"; const params = new URLSearchParams({ projectId, view }); if (lens.selectedPrdIds.length) params.set("prd", lens.selectedPrdIds.join(",")); if (lens.mode === "isolate") params.set("lens", "isolate"); return `/demo?${params.toString()}${destination.type === "fact" ? `#${destination.targetId}` : ""}`; }
function DestinationLink({ destination, lens, projectId }: { destination: ProjectWorkspaceFixture["changes"][number]["destination"]; lens: WorkspaceLens; projectId: string }) { if (destination.type === "unresolved" || destination.type === "project") return <span className="change-destination">{destination.label}</span>; return <Link href={destinationHref(projectId, lens, destination)}>Open destination →<small>{destination.label}</small></Link>; }
function Accounting({ prdId, projectId, lens, workspace, onClose, onSelectOnly }: { prdId: string; projectId: string; lens: WorkspaceLens; workspace: ProjectWorkspaceFixture; onClose: () => void; onSelectOnly: (id: string) => void }) { const prd = workspace.prds.find((item) => item.id === prdId)!; const statements = workspace.sourceAccounting.filter((item) => item.prdId === prdId); const placed = statements.filter((item) => item.destination.type !== "unresolved").length; return <Dialog onClose={onClose} title={`Source document accounting — ${prd.name}`}><section className="source-accounting-modal"><p>{prd.increment} · {prd.publishedAt}</p><div className="accounting-summary"><span><b>{statements.length}</b> statements found</span><span><b>{placed}</b> placed in project</span><span><b>{statements.length - placed}</b> needs an answer</span></div>{statements.map((statement) => <article className={statement.destination.type === "unresolved" ? "is-question" : ""} key={statement.id}><span>{statement.destination.type === "unresolved" ? "?" : "✓"}</span><div><small>Source statement</small><blockquote>“{statement.statement}”</blockquote><b>{statement.destination.label}</b></div><DestinationLink destination={statement.destination} lens={lens} projectId={projectId} /></article>)}<footer><p>Every source statement resolves to Main Workflow, Project Facts, CES Result, Needs Answer, or an explicit exclusion.</p><button onClick={() => onSelectOnly(prdId)} type="button">Use this PRD as global lens</button></footer></section></Dialog>; }
function Empty() { return <section className="knowledge-empty"><strong>No selected contribution here</strong><p>Choose another PRD or turn off isolation to restore the accumulated project context.</p></section>; }
