"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import type { ProjectFixture, ProjectWorkspaceFixture, WorkflowFixture, WorkflowNodeFixture } from "@atlas/fixtures";
import { AppShell } from "./AppShell";
import { useWorkspaceLens, type WorkspaceLens } from "./WorkspaceLens";

type User = { name: string; email: string; role: "owner" | "editor" | "viewer" };
const affected = (ids: string[], selected: string[]) => !selected.length || ids.some((id) => selected.includes(id));

export function WorkflowWorkspace({ user, projects, workspace, initialLens }: { user: User; projects: ProjectFixture[]; workspace: ProjectWorkspaceFixture; initialLens: WorkspaceLens }) {
  const { lens, set, toggle } = useWorkspaceLens(initialLens);
  const selected = lens.selectedPrdIds;
  const isolate = lens.mode === "isolate";
  const [lensOpen, setLensOpen] = useState(false);
  const lensRef = useRef<HTMLDivElement>(null);
  const [pageId, setPageId] = useState<string | null>(null);
  const [nodeId, setNodeId] = useState<string | null>(null);
  const lensActive = selected.length > 0;
  const affectedPages = useMemo(() => workspace.workflows.filter((page) => affected(page.prdIds, selected)), [selected, workspace.workflows]);
  const pages = isolate && lensActive ? affectedPages : workspace.workflows;
  const page = workspace.workflows.find((item) => item.id === pageId) ?? null;
  const group = workspace.workflowGroups.find((item) => item.id === page?.groupId);
  const selectedNode = page?.nodes.find((item) => item.id === nodeId) ?? null;
  const currentIndex = page ? pages.findIndex((item) => item.id === page.id) : -1;
  const affectedCount = affectedPages.length;
  const open = (id: string) => { setPageId(id); setNodeId(null); };
  const move = (direction: -1 | 1) => { if (pages.length) open(pages[(currentIndex + direction + pages.length) % pages.length].id); };
  const moveAffected = (direction: -1 | 1) => { const affectedIndex = affectedPages.findIndex((item) => item.id === page?.id); if (affectedPages.length) open(affectedPages[(Math.max(affectedIndex, 0) + direction + affectedPages.length) % affectedPages.length].id); };
  useEffect(() => {
    if (!lensOpen) return;
    const closeOnOutsideClick = (event: PointerEvent) => { if (!lensRef.current?.contains(event.target as Node)) setLensOpen(false); };
    document.addEventListener("pointerdown", closeOnOutsideClick);
    return () => document.removeEventListener("pointerdown", closeOnOutsideClick);
  }, [lensOpen]);
  return <AppShell active="workflow" projectNavigation projects={projects} routeContext={{ prd: selected.length ? selected.join(",") : undefined, lens: isolate && lensActive ? "isolate" : undefined }} selectedProjectId={workspace.project.id} topbarAction={<div className="topbar-prd-lens" ref={lensRef}><button aria-expanded={lensOpen} className="topbar-prd-trigger" onClick={() => setLensOpen((open) => !open)} type="button"><span>⌁</span><div><small>PRD lens</small><strong>{lensActive ? <>{selected.length} PRD{selected.length > 1 ? "s" : ""}<span className="lens-selected-suffix"> selected</span></> : "All PRDs"}</strong></div><i>⌄</i></button>{lensOpen && <div className="prd-lens-popover"><header><div><span className="workflow-kicker">Global project filter</span><strong>Choose one or more PRDs</strong></div><button aria-label="Close PRD lens" onClick={() => setLensOpen(false)} type="button">×</button></header><button className={!lensActive ? "is-selected" : ""} onClick={() => set({ selectedPrdIds: [], mode: "highlight" })} type="button"><span>{!lensActive ? "✓" : ""}</span><div><strong>All PRDs</strong><small>Complete accumulated project</small></div></button>{workspace.prds.map((prd) => <button className={selected.includes(prd.id) ? "is-selected" : ""} key={prd.id} onClick={() => toggle(prd.id)} type="button"><span>{selected.includes(prd.id) ? "✓" : ""}</span><div><strong>{prd.increment}</strong><small>{prd.name} · {prd.pageCount} pages</small></div></button>)}<label aria-label="Hide unselected PRD data" className={!lensActive ? "is-disabled" : ""}><input checked={isolate && lensActive} disabled={!lensActive} onChange={(event) => set({ ...lens, mode: event.target.checked ? "isolate" : "highlight" })} type="checkbox" /><i /> <div><strong>Hide unselected PRD data</strong><small>{isolate && lensActive ? "Isolation mode" : "Contextual highlight mode"}</small></div></label><footer><span>{lensActive ? isolate ? "Showing selected contributions and structural context." : "Showing accumulated context with selected contributions." : "Showing the complete accumulated project."}</span><button onClick={() => setLensOpen(false)} type="button">Done</button></footer></div>}</div>} user={user} workspace={workspace}><section className="workflow-page">
    {page ? isolate && lensActive && !affected(page.prdIds, selected) ? <IsolationEmpty onBack={() => { setPageId(null); setNodeId(null); }} /> : <Detail affectedCount={affectedCount} page={page} group={group?.title ?? "Workflow"} groups={workspace.workflowGroups} pages={pages} prds={workspace.prds} selected={selected} isolate={isolate} lensActive={lensActive} currentIndex={currentIndex} projectName={workspace.project.name} selectedNode={selectedNode} onBack={() => { setPageId(null); setNodeId(null); }} onMove={move} onMoveAffected={moveAffected} onOpen={open} onSelectNode={setNodeId} /> : <Overview workspace={workspace} selected={selected} isolate={isolate} lensActive={lensActive} affectedCount={affectedCount} onOpen={open} />}
  </section></AppShell>;
}

function Overview({ workspace, selected, isolate, lensActive, affectedCount, onOpen }: { workspace: ProjectWorkspaceFixture; selected: string[]; isolate: boolean; lensActive: boolean; affectedCount: number; onOpen: (id: string) => void }) {
  const groups = workspace.workflowGroups.filter((group) => !group.support && (!isolate || !lensActive || affected(group.prdIds, selected)));
  const support = workspace.workflowGroups.find((group) => group.support);
  return <><header className="workflow-overview-heading"><Link href="/demo">← Projects</Link><p className="workflow-kicker">Current accumulated understanding</p><h1>How Safara operates today</h1><p>Explore the accumulated operational understanding, then open any stage to inspect its source-grounded detail.</p><dl><div><dt>{groups.length}</dt><dd>major workflows</dd></div><div><dt>{workspace.workflows.length}</dt><dd>semantic pages</dd></div><div><dt>{workspace.prds.length}</dt><dd>source PRDs</dd></div></dl></header>
    {lensActive && <section className="workflow-impact"><div><span>⌁</span><p><strong>{isolate ? "Isolating selected PRD contributions" : "Selected PRDs in accumulated context"}</strong><small>{affectedCount} workflow pages contain contributions from the selected PRDs.</small></p></div><button onClick={() => { const first = workspace.workflows.find((page) => affected(page.prdIds, selected)); if (first) onOpen(first.id); }} type="button">Open first affected page →</button></section>}
    <section className="major-workflow-sequence" aria-label="Ordered major workflows">{groups.map((group, index) => { const matched = affected(group.prdIds, selected); return <article className={lensActive && !matched ? "is-muted" : ""} key={group.id}><button onClick={() => onOpen(group.workflowIds[0])} type="button"><header><span>{group.order}</span>{lensActive && matched && <em>{group.workflowIds.length} pages</em>}</header><div><h2>{group.title}</h2><p>{group.summary}</p></div><footer><small>Business result</small><strong>{group.expectedResult}</strong><span>{group.workflowIds.length} workflow {group.workflowIds.length === 1 ? "page" : "pages"}<b>Open group →</b></span></footer></button>{index < groups.length - 1 && <i>→</i>}</article>; })}</section>
    {support && <section className="workflow-support"><div><span className="workflow-kicker">Cross-workflow support</span><strong>{support.title}</strong><p>{support.summary}</p></div><div>{support.workflowIds.map((id) => <button key={id} onClick={() => onOpen(id)} type="button">{workspace.workflows.find((page) => page.id === id)?.title}<span>→</span></button>)}</div></section>}
    <footer className="overview-next"><p>Open a major workflow to enter its first semantic page. Continue through the accumulated model using the page navigator.</p><button onClick={() => onOpen(groups[0]?.workflowIds[0] ?? workspace.workflows[0].id)} type="button">Open the operational model →</button></footer></>;
}

function IsolationEmpty({ onBack }: { onBack: () => void }) {
  return <section className="workflow-isolation-empty"><span className="workflow-kicker">No selected contribution on this page</span><h1>Choose another PRD lens state</h1><p>This workflow has no contribution from the selected PRDs. Return to the overview to open an affected page, or change the lens to restore accumulated context.</p><button onClick={onBack} type="button">← Return to overview</button></section>;
}

function Detail({ page, group, groups, pages, prds, selected, isolate, lensActive, affectedCount, currentIndex, projectName, selectedNode, onBack, onMove, onMoveAffected, onOpen, onSelectNode }: { page: WorkflowFixture; group: string; groups: ProjectWorkspaceFixture["workflowGroups"]; pages: WorkflowFixture[]; prds: ProjectWorkspaceFixture["prds"]; selected: string[]; isolate: boolean; lensActive: boolean; affectedCount: number; currentIndex: number; projectName: string; selectedNode: WorkflowNodeFixture | null; onBack: () => void; onMove: (direction: -1 | 1) => void; onMoveAffected: (direction: -1 | 1) => void; onOpen: (id: string) => void; onSelectNode: (id: string | null) => void }) {
  const visibleNodes = page.nodes.filter((node, index, nodes) => !isolate || !lensActive || affected(node.prdIds, selected) || (index > 0 && affected(nodes[index - 1].prdIds, selected)));
  return <><nav className="semantic-pager" aria-label="Semantic workflow navigation"><button onClick={onBack} type="button">← Overview</button><button aria-label="Previous workflow page" onClick={() => onMove(-1)} type="button">←</button><select aria-label="Workflow page" onChange={(event) => onOpen(event.target.value)} value={page.id}>{groups.map((groupItem) => <optgroup key={groupItem.id} label={`${groupItem.order} · ${groupItem.title}`}>{pages.filter((item) => item.groupId === groupItem.id).map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</optgroup>)}</select><button aria-label="Next workflow page" onClick={() => onMove(1)} type="button">→</button>{lensActive && !isolate && <span>{affectedCount} affected pages <button aria-label="Previous affected workflow page" onClick={() => onMoveAffected(-1)} type="button">←</button><button aria-label="Next affected workflow page" onClick={() => onMoveAffected(1)} type="button">→</button></span>}</nav>
    <nav aria-label="Breadcrumb" className="workflow-breadcrumb"><span>{projectName}</span><span>Main Workflow</span><span>{group}</span><strong>{page.title}</strong></nav>
    <header className="semantic-heading"><div><p className="workflow-kicker">{group} · Page {String(currentIndex + 1).padStart(2, "0")} of {pages.length}</p><h1>{page.title}</h1><p>{page.summary} This page answers one business question without loading the entire project graph.</p></div><dl><div><dt>Who is involved</dt><dd>{page.roles.join(" · ")}</dd></div><div><dt>Business result</dt><dd>{page.expectedResult}</dd></div></dl></header>
    <section className="source-history"><div><span className="workflow-kicker">Source history</span><strong>Built from {page.prdIds.length} PRD{page.prdIds.length > 1 ? "s" : ""}</strong></div>{page.prdIds.map((id) => { const prd = prds.find((item) => item.id === id); return prd && <span className={selected.includes(id) ? "is-selected" : ""} key={id}><b>{prd.increment}</b><small>{prd.name} · {prd.publishedAt}</small></span>; })}<p>{lensActive ? "Selected contributions are marked in the workflow." : "Use the PRD lens to inspect provenance."}</p></section>
    <section className="semantic-flow"><header><div><span className="workflow-kicker">Semantic workflow page</span><h2>{page.businessQuestion}</h2></div><p>Select a step to verify its exact PRD wording.</p></header><div className="semantic-nodes">{visibleNodes.map((node, index) => { const matched = affected(node.prdIds, selected); const context = isolate && lensActive && !matched; return <div className="semantic-node-slot" key={node.id}><button className={`semantic-node ${node.kind} ${selectedNode?.id === node.id ? "is-selected" : ""} ${lensActive && matched ? "is-matched" : ""} ${context ? "is-context" : ""}`} onClick={() => onSelectNode(node.id)} type="button"><span>{String(index + 1).padStart(2, "0")}</span><strong>{node.title}</strong><p>{node.note}</p>{lensActive && <em>{context ? "Context" : matched ? "Selected PRD" : "Accumulated"}</em>}</button>{index < visibleNodes.length - 1 && <i>→</i>}</div>; })}</div><footer><span>□ Current page data</span>{lensActive && <span>▣ Selected PRD contribution</span>}{isolate && lensActive && <span>┄ Structural context</span>}</footer></section>
    <section className={`node-evidence ${selectedNode ? "is-open" : ""}`}>{selectedNode ? <><article><span className="workflow-kicker">What Atlas understood</span><h2>{selectedNode.title}</h2><p>{selectedNode.evidence.understood}</p></article><article><header><span className="workflow-kicker">Exact PRD wording</span><button onClick={() => onSelectNode(null)} type="button">Close</button></header><blockquote>“{selectedNode.evidence.quote}”</blockquote><footer>{selectedNode.evidence.documentName} · page {selectedNode.evidence.page}</footer></article></> : <p><strong>Select a workflow step</strong><br />Atlas interpretation and exact PRD wording will appear here.</p>}</section>
    <footer className="detail-continuation"><button onClick={() => onMove(-1)} type="button">← Previous workflow page</button><span>Page {currentIndex + 1} in the accumulated model</span><button onClick={() => onMove(1)} type="button">Next workflow page →</button></footer></>;
}
