"use client";

import { useEffect, useState, type FormEvent } from "react";
import { createPortal } from "react-dom";
import { createFixtureWorkspace, resolveFixtureWorkspaceInventory, type PrdFileMetadata, type WorkspaceCreationBase } from "@atlas/fixtures";
import { AppShell } from "./AppShell";
import { Button } from "./Button";
import { Dialog } from "./Dialog";
import { WorkspaceSwitcher, type WorkspaceSwitcherModel } from "./WorkspaceSwitcher";

const inventory = resolveFixtureWorkspaceInventory("safara");
const defaultWorkspaceId = "branch-increment-003";
const baseRecords: WorkspaceCreationBase[] = inventory.map((workspace) => ({ workspaceId: workspace.workspaceId, projectId: workspace.projectId, baseWorkspaceId: workspace.baseWorkspaceId, headRevisionId: workspace.headRevisionId }));
const workspaceItem = (workspace: typeof inventory[number]): WorkspaceSwitcherModel["workspaces"][number] => ({ id: workspace.workspaceId, name: workspace.name, status: workspace.status, prdCount: workspace.prdCount, base: workspace.baseWorkspaceId ? inventory.find((item) => item.workspaceId === workspace.baseWorkspaceId)?.name : undefined, createdBy: workspace.createdBy, createdAt: workspace.createdAt, modifiedBy: workspace.modifiedBy, modifiedAt: workspace.modifiedAt, relative: workspace.relative, displayedHead: workspace.headRevisionId, executionProvenance: workspace.executionProvenance, unavailableReason: workspace.unavailableReason });
export const workspaceSwitcherPreviewModel: WorkspaceSwitcherModel = { projectName: "Safara", selectedId: defaultWorkspaceId, workspaces: inventory.map(workspaceItem) };
const previewProject = { id: "safara", name: "Safara", status: "ready" as const, prdCount: 3, collaborators: 4, lastActivity: "Active", isShared: false, repository: { state: "published" as const, summary: "", master: { state: "published" as const, summary: "", detail: "" }, metrics: [{ value: "", label: "" }, { value: "", label: "" }, { value: "", label: "" }] as [{ value: string; label: string }, { value: string; label: string }, { value: string; label: string }], action: { label: "Open project", enabled: true } } };
export function WorkspaceSwitcherDemoHost({ initialWorkspaceId = workspaceSwitcherPreviewModel.selectedId, projectId = "safara", projectName, unavailableWorkspaceName }: { initialWorkspaceId?: string; projectId?: string; projectName: string; unavailableWorkspaceName?: string }) {
  const routeInventory = resolveFixtureWorkspaceInventory(projectId);
  const routeItems = routeInventory.map((workspace) => ({ id: workspace.workspaceId, name: workspace.name, status: workspace.status, prdCount: workspace.prdCount, base: workspace.baseWorkspaceId ? routeInventory.find((item) => item.workspaceId === workspace.baseWorkspaceId)?.name : undefined, createdBy: workspace.createdBy, createdAt: workspace.createdAt, modifiedBy: workspace.modifiedBy, modifiedAt: workspace.modifiedAt, relative: workspace.relative, displayedHead: workspace.headRevisionId, executionProvenance: workspace.executionProvenance, unavailableReason: workspace.unavailableReason }));
  const [selectedId, setSelectedId] = useState(initialWorkspaceId);
  const [routeNotice, setRouteNotice] = useState(unavailableWorkspaceName ? `${unavailableWorkspaceName} is still extracting and cannot be opened.` : "");
  const [createdWorkspaces, setCreatedWorkspaces] = useState<WorkspaceSwitcherModel["workspaces"]>([]);
  const [createOpen, setCreateOpen] = useState(false);
  const [workspaceName, setWorkspaceName] = useState("");
  const [baseWorkspaceId, setBaseWorkspaceId] = useState(initialWorkspaceId);
  const [prdFiles, setPrdFiles] = useState<File[]>([]);
  const [submitState, setSubmitState] = useState<"idle" | "loading" | "error">("idle");
  const [errors, setErrors] = useState<Partial<Record<"workspaceName" | "prdFiles" | "request", string>>>({});
  useEffect(() => { const sync = () => { const requested = new URLSearchParams(window.location.search).get("workspaceId"); if (requested && workspaceSwitcherPreviewModel.workspaces.some((workspace) => workspace.id === requested && !workspaceSwitcherPreviewModel.workspaces.find((workspace) => workspace.id === requested)?.unavailableReason)) setSelectedId(requested); }; window.addEventListener("popstate", sync); return () => window.removeEventListener("popstate", sync); }, []);
  const select = (workspaceId: string) => { setSelectedId(workspaceId); const url = new URL(window.location.href); url.searchParams.set("workspaceId", workspaceId); window.history.replaceState(null, "", url); window.dispatchEvent(new Event("atlas-workspace-selection")); setRouteNotice(""); };
  const resetCreateForm = () => { setWorkspaceName(""); setBaseWorkspaceId(selectedId); setPrdFiles([]); setErrors({}); setSubmitState("idle"); };
  const closeCreate = () => { setCreateOpen(false); resetCreateForm(); };
  const createTokens = () => Array.from({ length: 2 }, () => { let value = BigInt(`0x${crypto.randomUUID().replace(/-/g, "")}`); let token = ""; for (let index = 0; index < 12; index += 1) { token = "abcdefghijklmnopqrstuvwxyz234567"[Number(value & 31n)] + token; value >>= 5n; } return token; });
  const createWorkspace = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const nextErrors: Partial<Record<"workspaceName" | "prdFiles", string>> = {}; if (!workspaceName.trim()) nextErrors.workspaceName = "Enter a workspace name."; if (!prdFiles.length) nextErrors.prdFiles = "Select at least one PRD PDF."; else if (prdFiles.some((file) => file.type !== "application/pdf")) nextErrors.prdFiles = "Only PDF files can be added."; setErrors(nextErrors); if (Object.keys(nextErrors).length) { setSubmitState("error"); return; } setSubmitState("loading"); try { const created = createFixtureWorkspace({ projectId: "safara", workspaceName, baseWorkspaceId, prdFiles: prdFiles.map((file): PrdFileMetadata => ({ name: file.name, type: "application/pdf", size: file.size })) }, [...baseRecords, ...createdWorkspaces.map((workspace) => ({ workspaceId: workspace.id, projectId: "safara", baseWorkspaceId: inventory.find((item) => item.name === workspace.base)?.workspaceId, headRevisionId: workspace.displayedHead ?? "pending extraction" }))], createTokens()); const base = inventory.find((workspace) => workspace.workspaceId === created.workspace.baseWorkspaceId); setCreatedWorkspaces((current) => [...current, { id: created.workspace.workspaceId, name: created.workspace.workspaceName, status: "Processing", prdCount: created.workspace.prdFiles.length, base: base?.name ?? created.workspace.baseWorkspaceId, createdBy: "Aditya", createdAt: new Date().toISOString(), modifiedBy: "Aditya", modifiedAt: new Date().toISOString(), relative: "Just now", displayedHead: "pending extraction", executionProvenance: "codex · extracting", unavailableReason: created.workspace.unavailableReason }]); setRouteNotice(`${created.workspace.workspaceName} was created. Extraction is in progress, so it cannot be opened yet.`); setCreateOpen(false); resetCreateForm(); } catch (error) { setSubmitState("error"); setErrors({ request: error instanceof Error ? error.message : "Workspace could not be created." }); } };
  const model: WorkspaceSwitcherModel = { projectName, selectedId, workspaces: [...routeItems, ...createdWorkspaces] };
  const modal = <Dialog onClose={closeCreate} title="New workspace"><form className="new-workspace-form" noValidate onSubmit={createWorkspace}><p className="form-intro">Create a workspace from an existing branch and PRD PDFs. Atlas captures the base revision automatically.</p><label htmlFor="workspace-name">Workspace name <span>* Required</span><input aria-describedby="workspace-name-error" aria-invalid={Boolean(errors.workspaceName)} id="workspace-name" onChange={(event) => setWorkspaceName(event.target.value)} required value={workspaceName} /></label>{errors.workspaceName && <p className="field-error" id="workspace-name-error" role="alert">{errors.workspaceName}</p>}<label htmlFor="workspace-base">Base workspace <span>* Required</span><select id="workspace-base" onChange={(event) => setBaseWorkspaceId(event.target.value)} value={baseWorkspaceId}>{inventory.filter((workspace) => workspace.available).map((workspace) => <option key={workspace.workspaceId} value={workspace.workspaceId}>{workspace.name}</option>)}</select></label><p className="field-help">Atlas snapshots the selected base workspace’s current HEAD; it is not editable here.</p><label htmlFor="workspace-prds">PRD PDFs <span>* Required</span><input accept="application/pdf,.pdf" aria-describedby="workspace-prds-help workspace-prds-error" id="workspace-prds" multiple onChange={(event) => setPrdFiles(Array.from(event.target.files ?? []))} required type="file" /></label><p className="field-help" id="workspace-prds-help">{prdFiles.length ? `${prdFiles.length} PDF${prdFiles.length === 1 ? "" : "s"} selected. Files and extraction are simulated in this prototype.` : "Select one or more PDF files."}</p>{errors.prdFiles && <p className="field-error" id="workspace-prds-error" role="alert">{errors.prdFiles}</p>}{errors.request && <p className="field-error" role="alert">{errors.request}</p>}<div className="dialog-actions"><Button disabled={submitState === "loading"} type="submit">{submitState === "loading" ? "Creating…" : "Create workspace"}</Button></div></form></Dialog>;
  return <><p aria-live="polite" className="sr-only">{routeNotice}</p><WorkspaceSwitcher model={model} onNewWorkspace={() => { resetCreateForm(); setCreateOpen(true); }} onSelect={select} />{createOpen && createPortal(modal, document.body)}</>;
}
export function WorkspaceSwitcherPreview() { return <AppShell active="workflow" projectNavigation projects={[previewProject]} routeContext={{ workspaceId: "branch-increment-003" }} selectedProjectId="safara" sidebarCollapsible={false} user={{ name: "Aditya", email: "aditya@example.com", role: "owner" }} workspaceSwitcher={<WorkspaceSwitcherDemoHost projectName="Safara" />}><section className="workspace-switcher-preview"><p className="eyebrow">Main workflow</p><h1>Safara operational model</h1><p>The workspace selector changes which accepted HEAD Atlas treats as current truth without replaying every source PRD.</p></section></AppShell>; }
