"use client";

import { useEffect, useState } from "react";
import { resolveFixtureWorkspaceInventory } from "@atlas/fixtures";
import { AppShell } from "./AppShell";
import { WorkspaceSwitcher, type WorkspaceSwitcherModel } from "./WorkspaceSwitcher";

const inventory = resolveFixtureWorkspaceInventory("safara");
export const workspaceSwitcherPreviewModel: WorkspaceSwitcherModel = { projectName: "Safara", selectedId: "branch-increment-003", workspaces: inventory.map((workspace) => ({ id: workspace.workspaceId, name: workspace.name, status: workspace.status, prdCount: workspace.prdCount, base: workspace.baseWorkspaceId ? inventory.find((item) => item.workspaceId === workspace.baseWorkspaceId)?.name : undefined, createdBy: workspace.createdBy, createdAt: workspace.createdAt, modifiedBy: workspace.modifiedBy, modifiedAt: workspace.modifiedAt, relative: workspace.relative, displayedHead: workspace.headRevisionId, executionProvenance: workspace.executionProvenance, unavailableReason: workspace.unavailableReason })) };
const previewProject = { id: "safara", name: "Safara", status: "ready" as const, prdCount: 3, collaborators: 4, lastActivity: "Active", isShared: false, repository: { state: "published" as const, summary: "", master: { state: "published" as const, summary: "", detail: "" }, metrics: [{ value: "", label: "" }, { value: "", label: "" }, { value: "", label: "" }] as [{ value: string; label: string }, { value: string; label: string }, { value: string; label: string }], action: { label: "Open project", enabled: true } } };
export function WorkspaceSwitcherDemoHost({ initialWorkspaceId = workspaceSwitcherPreviewModel.selectedId, projectName, unavailableWorkspaceName }: { initialWorkspaceId?: string; projectName: string; unavailableWorkspaceName?: string }) {
  const [selectedId, setSelectedId] = useState(initialWorkspaceId);
  const [routeNotice, setRouteNotice] = useState(unavailableWorkspaceName ? `${unavailableWorkspaceName} is still extracting and cannot be opened.` : "");
  useEffect(() => { const sync = () => { const requested = new URLSearchParams(window.location.search).get("workspaceId"); if (requested && workspaceSwitcherPreviewModel.workspaces.some((workspace) => workspace.id === requested && !workspaceSwitcherPreviewModel.workspaces.find((workspace) => workspace.id === requested)?.unavailableReason)) setSelectedId(requested); }; window.addEventListener("popstate", sync); return () => window.removeEventListener("popstate", sync); }, []);
  const select = (workspaceId: string) => { setSelectedId(workspaceId); const url = new URL(window.location.href); url.searchParams.set("workspaceId", workspaceId); window.history.replaceState(null, "", url); window.dispatchEvent(new Event("atlas-workspace-selection")); setRouteNotice(""); };
  return <><p aria-live="polite" className="sr-only">{routeNotice}</p><WorkspaceSwitcher model={{ ...workspaceSwitcherPreviewModel, projectName, selectedId }} onSelect={select} /></>;
}
export function WorkspaceSwitcherPreview() { return <AppShell active="workflow" projectNavigation projects={[previewProject]} routeContext={{ workspaceId: "branch-increment-003" }} selectedProjectId="safara" sidebarCollapsible={false} user={{ name: "Aditya", email: "aditya@example.com", role: "owner" }} workspaceSwitcher={<WorkspaceSwitcherDemoHost projectName="Safara" />}><section className="workspace-switcher-preview"><p className="eyebrow">Main workflow</p><h1>Safara operational model</h1><p>The workspace selector changes which accepted HEAD Atlas treats as current truth without replaying every source PRD.</p></section></AppShell>; }
